import type { BlogPost } from "./types";

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "meest-gemaakte-fouten-op-een-cv",
    title: "De 7 meest gemaakte fouten op een cv (en hoe je ze voorkomt)",
    description:
      "Ontdek de 7 meest gemaakte fouten op een cv en hoe je ze voorkomt. Praktische tips voor de Nederlandse arbeidsmarkt, inclusief ATS-proof voorbeelden.",
    excerpt:
      "De meeste cv's vallen af om dezelfde zeven redenen. Leer welke fouten Nederlandse werkzoekenden maken en hoe je ze stap voor stap voorkomt.",
    date: "2025-06-03",
    dateLabel: "3 juni 2025",
    readTime: "8 min",
    author: "CVmaken.nu Team",
    categories: ["CV Tips", "ATS"],
    keywords: [
      "fouten op een cv",
      "cv fouten voorkomen",
      "ATS-proof cv",
      "cv tips Nederland",
      "cv schrijven",
      "professioneel cv maken",
      "cv afgewezen redenen",
    ],
    content: [
      { type: "p", text: "Recruiters kijken gemiddeld maar een paar seconden naar je cv voordat ze beslissen of ze verder lezen. In die paar seconden kun je het verschil maken, of jezelf onbedoeld uit de race halen. Het goede nieuws: de meeste cv's stranden om steeds dezelfde redenen. Hieronder bespreken we de zeven meest gemaakte fouten op een cv binnen de Nederlandse arbeidsmarkt, met concrete voorbeelden van wat niet werkt en wat wel. Loop ze stuk voor stuk na voordat je solliciteert." },
      { type: "h2", text: "Fout 1: Een vaag en algemeen profiel" },
      { type: "p", text: "Je profiel staat bovenaan en is het eerste dat een recruiter leest. Toch vullen veel mensen het met holle frasen die voor iedereen gelden. Zinnen als 'gemotiveerde professional die graag het beste uit zichzelf haalt' zeggen helemaal niets over jou." },
      { type: "p", text: "Fout: 'Enthousiaste en betrokken medewerker met passie voor mijn vak en oog voor detail.'" },
      { type: "p", text: "Goed: 'Financieel medewerker met 6 jaar ervaring in de logistiek. Verkortte bij mijn huidige werkgever de maandafsluiting van 8 naar 3 werkdagen. Zoek een functie waarin ik processen verder kan automatiseren.'" },
      { type: "p", text: "Maak het profiel specifiek voor jouw rol, jouw cijfers en de vacature waarop je solliciteert. Hoe concreter, hoe geloofwaardiger." },
      { type: "h2", text: "Fout 2: Taken opsommen in plaats van resultaten" },
      { type: "p", text: "Dit is misschien wel de meest voorkomende fout. Mensen kopieren letterlijk hun functieomschrijving in het cv. Maar een recruiter wil niet weten wat je moest doen, hij wil weten wat je hebt bereikt." },
      { type: "p", text: "Fout: 'Verantwoordelijk voor de klantenservice en het beantwoorden van vragen.'" },
      { type: "p", text: "Goed: 'Verlaagde de gemiddelde reactietijd van klantvragen met 40% en verhoogde de klanttevredenheid (NPS) van 32 naar 51 in een jaar.'" },
      { type: "p", text: "Begin elk punt met een actiewerkwoord en koppel er waar mogelijk een cijfer aan: een percentage, een bedrag, een aantal of een tijdsbesparing. Niet elke prestatie is in een cijfer te vatten, maar streef ernaar bij minstens de helft van je punten." },
      { type: "callout", title: "Praktische tip: de STAR-formule kort", text: "Geen cijfers paraat? Beschrijf dan de Situatie, je Actie en het Resultaat in een zin. Voorbeeld: 'Bij een terugkerende klacht over levertijden een nieuw planningssysteem ingevoerd, waardoor klachten merkbaar afnamen.'" },
      { type: "h2", text: "Fout 3: ATS-onvriendelijke opmaak" },
      { type: "p", text: "Veel werkgevers, en vrijwel alle uitzendbureaus, gebruiken een Applicant Tracking System (ATS) dat cv's automatisch inleest. Mooie tabellen, twee kolommen, tekstvakken, iconen en foto's op de verkeerde plek kunnen ervoor zorgen dat de software je cv verkeerd of helemaal niet leest." },
      { type: "p", text: "Veelgemaakte opmaakfouten die een ATS in de war brengen:" },
      { type: "ul", items: ["Belangrijke informatie in tabellen of tekstvakken zetten", "Je werkervaring in twee kolommen naast elkaar plaatsen", "Contactgegevens in de kop- of voettekst verbergen", "Vaardigheden weergeven als grafieken of voortgangsbalkjes zonder tekst", "Het cv als afbeelding of als gescand document opslaan"] },
      { type: "p", text: "Houd het simpel: een duidelijke chronologische indeling, standaard kopjes zoals 'Werkervaring' en 'Opleiding', en bewaar je cv als doorzoekbare PDF. In Nederland is een nette foto bovenaan gebruikelijk en geen probleem, zolang de tekst eromheen gewoon leesbaar blijft voor de software." },
      { type: "h2", text: "Fout 4: Spel- en grammaticafouten" },
      { type: "p", text: "Een typefout in je cv is klein, maar de boodschap die een recruiter eruit haalt is groot: deze kandidaat heeft niet goed opgelet. Bij functies waar nauwkeurigheid telt, kan een enkele fout je al de kop kosten. Veelvoorkomende missers zijn d/t-fouten, 'als' versus 'dan', en het door elkaar gebruiken van Engelse en Nederlandse termen." },
      { type: "ul", items: ["Lees je cv hardop voor, dan hoor je kromme zinnen sneller", "Laat iemand anders meelezen die de tekst niet kent", "Gebruik een spellingcontrole, maar vertrouw er niet blind op", "Wees consequent: kies voor Nederlands of Engels en wissel niet"] },
      { type: "h2", text: "Fout 5: Te lang (meer dan twee pagina's)" },
      { type: "p", text: "Op de Nederlandse arbeidsmarkt geldt: een cv past op een of twee pagina's. Heb je net je opleiding afgerond of minder dan vijf jaar ervaring, houd het dan op een pagina. Pas bij ruime ervaring of een specialistische carriere is twee pagina's verdedigbaar. Drie pagina's of meer komt vrijwel altijd over als 'kan geen hoofdzaken van bijzaken scheiden'." },
      { type: "p", text: "Schrap baantjes van meer dan vijftien jaar geleden, bijbaantjes die niet relevant zijn en lange opsommingen van hobby's. Kies kwaliteit boven volledigheid." },
      { type: "quote", text: "Een recruiter onthoudt niet alles wat op je cv staat, maar wel het gevoel dat het hem gaf. Maak dat gevoel scherp en overzichtelijk." },
      { type: "h2", text: "Fout 6: Ontbrekende of onprofessionele contactgegevens" },
      { type: "p", text: "Het klinkt vanzelfsprekend, maar het gaat verrassend vaak mis. Een cv zonder telefoonnummer, of met een e-mailadres als 'feestbeest_1994@hotmail.com', maakt direct een verkeerde indruk." },
      { type: "p", text: "Zorg dat bovenaan je cv duidelijk staan:" },
      { type: "ul", items: ["Je volledige naam", "Een professioneel e-mailadres, bij voorkeur met je voor- en achternaam", "Een telefoonnummer waarop je echt bereikbaar bent", "Je woonplaats (een volledig adres is niet meer nodig)", "Eventueel een link naar je LinkedIn-profiel of portfolio"] },
      { type: "p", text: "Controleer ook of je LinkedIn-profiel klopt met je cv. Recruiters checken het standaard, en tegenstrijdigheden roepen vragen op." },
      { type: "h2", text: "Fout 7: Niet afgestemd op de vacature" },
      { type: "p", text: "Een en hetzelfde cv naar tien verschillende vacatures sturen is de snelste route naar tien afwijzingen. Elke vacature vraagt om een net iets andere nadruk. De woorden die de werkgever gebruikt in de vacaturetekst zijn vaak precies de termen waar een ATS op filtert." },
      { type: "p", text: "Stem je cv per sollicitatie af door:" },
      { type: "ol", items: ["De vacature te lezen en de drie belangrijkste eisen te markeren", "Je profiel en je eerste werkervaringen op die eisen aan te scherpen", "Dezelfde kernwoorden te gebruiken die in de vacature staan, mits ze echt op jou van toepassing zijn", "Irrelevante ervaring naar achteren te schuiven of weg te laten"] },
      { type: "p", text: "Dit kost vijf tot tien minuten per sollicitatie en verhoogt je kansen aanzienlijk." },
      { type: "h2", text: "Conclusie" },
      { type: "p", text: "De meeste cv's vallen niet af door gebrek aan talent, maar door vermijdbare fouten. Een scherp profiel, resultaten in plaats van taken, een ATS-vriendelijke opmaak, foutloze tekst, een compacte lengte, kloppende contactgegevens en een cv dat is afgestemd op de vacature: wie deze zeven punten op orde heeft, steekt direct boven het gemiddelde uit. Loop je cv nog een keer langs deze lijst voordat je op verzenden klikt." },
    ],
    faq: [
      { q: "Hoe lang mag een cv in Nederland zijn?", a: "Een Nederlands cv is bij voorkeur een tot twee pagina's. Met weinig ervaring houd je het op een pagina; alleen bij ruime of specialistische ervaring is twee pagina's gepast. Drie of meer pagina's wordt afgeraden." },
      { q: "Mag er een foto op een Nederlands cv?", a: "Ja, in Nederland is een nette, professionele foto bovenaan gebruikelijk en geaccepteerd. Zorg er wel voor dat de foto de leesbaarheid voor een ATS niet verstoort en plaats belangrijke tekst niet in of over de afbeelding." },
      { q: "Wat is een ATS en waarom is dat belangrijk?", a: "Een ATS (Applicant Tracking System) is software die cv's automatisch inleest en filtert. Een onleesbare opmaak met tabellen, kolommen of afbeeldingen kan ervoor zorgen dat je cv verkeerd wordt verwerkt en je sollicitatie nooit door een mens wordt gezien." },
      { q: "Moet ik mijn cv per vacature aanpassen?", a: "Ja. Stem je profiel en de nadruk in je werkervaring af op de eisen in de vacature en gebruik dezelfde kernwoorden. Dit kost enkele minuten per sollicitatie en verhoogt je kans om door de eerste selectie te komen." },
    ],
  },
  {
    slug: "profiel-dat-recruiters-bijblijft",
    title: "Hoe schrijf je een profiel dat recruiters bijblijft?",
    description:
      "Leer hoe je een cv-profiel schrijft dat recruiters onthouden. Met de 3-zinnen formule, clichés om te vermijden en concrete voorbeelden per functie.",
    excerpt:
      "Het profiel bovenaan je cv bepaalt of een recruiter doorleest. Leer met een simpele formule en voorbeelden hoe je er een schrijft die blijft hangen.",
    date: "2025-05-20",
    dateLabel: "20 mei 2025",
    readTime: "7 min",
    author: "CVmaken.nu Team",
    categories: ["Profiel schrijven"],
    keywords: ["cv profiel schrijven", "profielschets cv", "persoonlijk profiel cv", "cv samenvatting", "profiel voorbeeld cv", "over mij cv", "recruiter aandacht trekken"],
    content: [
      { type: "p", text: "Het profiel, ook wel persoonlijk profiel, profielschets of samenvatting genoemd, is het korte tekstje bovenaan je cv. Het is het allereerste dat een recruiter leest en bepaalt vaak of hij of zij doorgaat naar de rest. Toch besteden veel mensen er nauwelijks aandacht aan en vullen het met algemeenheden. Zonde, want juist hier kun je in een paar zinnen laten zien waarom jij de juiste kandidaat bent. In dit artikel lees je waar het profiel voor dient, hoe je het opbouwt met een simpele formule, welke clichés je moet vermijden, en zie je concrete voorbeelden per functie." },
      { type: "h2", text: "Waar dient het profiel voor?" },
      { type: "p", text: "Een recruiter scant je cv eerst razendsnel. Het profiel is jouw kans om in vier of vijf seconden de belangrijkste boodschap over te brengen: wie je bent, wat je kunt en wat je zoekt. Zie het als de pitch van je cv. Een sterk profiel zet de toon en zorgt dat de recruiter de rest van je cv leest met de juiste bril op." },
      { type: "p", text: "Het profiel is geen samenvatting van je hele leven en zeker geen motivatiebrief. Houd het kort: drie tot vier zinnen, of maximaal vijf à zes regels. Alles wat langer is, wordt toch overgeslagen." },
      { type: "h2", text: "De 3-zinnen formule" },
      { type: "p", text: "Een goed profiel beantwoordt in essentie drie vragen. Behandel ze elk in ongeveer een zin en je hebt een complete, krachtige profielschets." },
      { type: "ol", items: ["Wie ben je? Noem je functie of vakgebied en je jaren relevante ervaring.", "Wat kun je? Benoem je sterkste vaardigheid of een concreet resultaat dat jou onderscheidt.", "Wat zoek je? Vertel kort wat voor functie of uitdaging je nu zoekt."] },
      { type: "p", text: "Een voorbeeld waarin de drie zinnen samenkomen:" },
      { type: "quote", text: "Marketeer met 5 jaar ervaring in e-commerce. Verhoogde de online omzet van een webshop met 35% door een nieuwe contentstrategie. Op zoek naar een functie waarin ik data en creativiteit kan combineren om groei te realiseren." },
      { type: "callout", title: "Praktische tip: schrijf het profiel als laatste", text: "Vul eerst je werkervaring en resultaten in. Pak vervolgens je sterkste prestatie eruit en verwerk die in zin 2 van je profiel. Zo bouw je je profiel op feiten en niet op holle woorden." },
      { type: "h2", text: "Vermijd deze clichés" },
      { type: "p", text: "Sommige woorden komen op zoveel cv's voor dat ze hun betekenis volledig hebben verloren. Een recruiter leest eroverheen of haakt zelfs af. De grootste boosdoeners:" },
      { type: "ul", items: ["Resultaatgericht", "Teamspeler", "Proactief", "Stressbestendig", "Gedreven en gemotiveerd", "Hands-on mentaliteit", "Communicatief sterk"] },
      { type: "p", text: "Het probleem is niet dat deze eigenschappen onbelangrijk zijn, maar dat iedereen ze claimt en niemand ze bewijst. De oplossing: vervang de eigenschap door het bewijs ervan." },
      { type: "p", text: "In plaats van 'resultaatgericht': 'Haalde drie kwartalen op rij mijn verkoopdoel met gemiddeld 15% boven target.'" },
      { type: "p", text: "In plaats van 'teamspeler': 'Leidde een team van vijf collega's door een drukke piekperiode zonder vertraging in de levering.'" },
      { type: "p", text: "Laat de recruiter zelf concluderen dat je resultaatgericht en een teamspeler bent. Dat is veel overtuigender dan het opschrijven." },
      { type: "h2", text: "Stem je profiel af op de vacature" },
      { type: "p", text: "Een profiel dat blijft hangen, sluit aan op wat de werkgever zoekt. Lees de vacature en let op de eisen en de woorden die de werkgever gebruikt. Verwerk de meest relevante daarvan in je profiel, mits ze echt op jou van toepassing zijn." },
      { type: "p", text: "Solliciteer je op een functie waarin projectmanagement centraal staat? Zet dan je ervaring met projecten in zin 1 en 2, ook als je dat op een ander cv minder zou benadrukken. Eenzelfde basisprofiel kun je per sollicitatie in een paar minuten aanscherpen. Dat kleine verschil valt op." },
      { type: "h2", text: "Concrete voorbeelden per functie" },
      { type: "p", text: "Hieronder zie je per type rol een voorbeeld van een zwak profiel en een sterk profiel volgens de 3-zinnen formule." },
      { type: "h3", text: "Starter (net afgestudeerd)" },
      { type: "p", text: "Zwak: 'Enthousiaste starter die graag wil leren en gemotiveerd is om aan de slag te gaan.'" },
      { type: "p", text: "Sterk: 'Afgestudeerd HBO Communicatie met stage-ervaring bij een PR-bureau. Schreef daar wekelijks content die de bereikcijfers op social media verdubbelde. Zoek een eerste baan als junior communicatiemedewerker.'" },
      { type: "h3", text: "Professional met ervaring" },
      { type: "p", text: "Zwak: 'Ervaren en resultaatgerichte projectmanager met goede communicatieve vaardigheden.'" },
      { type: "p", text: "Sterk: 'Projectmanager met 8 jaar ervaring in de bouwsector. Leverde projecten tot 2 miljoen euro consistent binnen budget en planning op. Op zoek naar een rol waarin ik grotere, complexere projecten kan aansturen.'" },
      { type: "h3", text: "Carriereswitcher" },
      { type: "p", text: "Zwak: 'Op zoek naar een nieuwe uitdaging in een ander vakgebied.'" },
      { type: "p", text: "Sterk: 'Voormalig horecamanager die overstapt naar de IT. Rondde een omscholing tot front-end developer af en bouwde in mijn vrije tijd drie volledige webapplicaties. Zoek een junior developersrol waarin ik mijn klantgerichtheid en nieuwe techniek combineer.'" },
      { type: "h2", text: "Conclusie" },
      { type: "p", text: "Een profiel dat recruiters bijblijft, is kort, concreet en afgestemd op de vacature. Gebruik de 3-zinnen formule om in een oogopslag te laten zien wie je bent, wat je kunt en wat je zoekt. Vervang clichés door bewijs en stem je tekst per sollicitatie af. Schrijf je profiel als laatste, op basis van je eigen resultaten, en je hebt een opening die een recruiter aanzet om door te lezen." },
    ],
    faq: [
      { q: "Hoe lang moet een cv-profiel zijn?", a: "Houd je profiel kort: drie tot vier zinnen, of maximaal vijf à zes regels. Een recruiter leest het in enkele seconden, dus alles wat langer is wordt vaak overgeslagen." },
      { q: "Wat is het verschil tussen een profiel en een motivatiebrief?", a: "Het profiel is een korte samenvatting bovenaan je cv die in een paar zinnen laat zien wie je bent, wat je kunt en wat je zoekt. De motivatiebrief is een apart, uitgebreider document waarin je toelicht waarom je deze specifieke functie en werkgever wilt." },
      { q: "Welke woorden kun je beter niet in je profiel gebruiken?", a: "Vermijd uitgekauwde clichés als 'resultaatgericht', 'teamspeler', 'proactief' en 'stressbestendig'. Vervang ze door concreet bewijs, zoals een cijfer of een prestatie, zodat de recruiter zelf die conclusie trekt." },
      { q: "Moet ik mijn profiel per vacature aanpassen?", a: "Ja. Stem je profiel af op de eisen en kernwoorden in de vacature, mits ze echt op jou van toepassing zijn. Een basisprofiel kun je per sollicitatie in een paar minuten aanscherpen, en dat kleine verschil valt op." },
    ],
  },
  {
    slug: "ats-uitgelegd-automatische-cv-filtering",
    title: "ATS uitgelegd: zo werkt automatische cv-filtering",
    description:
      "ATS uitgelegd: ontdek hoe een Applicant Tracking System je cv leest, scoort en filtert, plus een checklist om je cv ATS-proof te maken.",
    excerpt:
      "Veel grote werkgevers laten je cv eerst door software lezen voordat een recruiter het ziet. Zo werkt een ATS en zo zorg je dat je cv erdoorheen komt.",
    date: "2025-05-12",
    dateLabel: "12 mei 2025",
    readTime: "8 min",
    author: "CVmaken.nu Team",
    categories: ["ATS"],
    keywords: ["ATS", "applicant tracking system", "cv ATS-proof maken", "automatische cv-filtering", "cv keywords", "cv door ATS", "sollicitatie software", "cv scannen"],
    content: [
      { type: "p", text: "Je hebt uren besteed aan je cv, op verzenden gedrukt en vervolgens niets gehoord. Grote kans dat een recruiter je cv nooit heeft gezien, maar dat een stuk software het eerst beoordeelde. Dat systeem heet een ATS, oftewel Applicant Tracking System. In dit artikel leggen we precies uit hoe een ATS je cv leest, scoort en filtert, en wat je concreet kunt doen om er gegarandeerd doorheen te komen." },
      { type: "h2", text: "Wat is een ATS precies?" },
      { type: "p", text: "Een Applicant Tracking System is software waarmee werkgevers sollicitaties verzamelen, ordenen en voorselecteren. Zodra je solliciteert via een vacaturepagina of een sollicitatieformulier, belandt je cv vaak niet direct in de inbox van een recruiter, maar in zo'n systeem. Het ATS pakt je cv uit, zet de inhoud om naar leesbare data en koppelt die aan de eisen uit de vacature." },
      { type: "p", text: "Bekende systemen die je in Nederland tegenkomt zijn onder andere Workday, SAP SuccessFactors, Greenhouse, Recruitee en AFAS. De recruiter ziet daarna een overzicht van kandidaten, vaak met een score of een match-percentage erbij. Wie laag scoort, zakt naar onderen of valt buiten beeld." },
      { type: "h2", text: "Waarom gebruiken zoveel Nederlandse werkgevers een ATS?" },
      { type: "p", text: "Het simpele antwoord is volume. Een populaire vacature bij een groot bedrijf levert al snel honderden reacties op. Handmatig elk cv lezen is dan onbegonnen werk. Naar schatting werkt ruim 70 procent van de grote Nederlandse werkgevers met een ATS, en bij multinationals, banken, verzekeraars, retailketens en de overheid is het vrijwel standaard." },
      { type: "p", text: "Voor jou als sollicitant betekent dit een belangrijke verschuiving: je schrijft je cv niet meer alleen voor een mens, maar ook voor een machine die als eerste poortwachter optreedt. Komt je cv niet door die eerste filter, dan doet de kwaliteit van je ervaring er niet eens toe." },
      { type: "callout", title: "De eerste lezer is geen mens", text: "Ga er bij grote en middelgrote werkgevers vanuit dat software je cv als eerste beoordeelt. Schrijf daarom zowel voor het systeem als voor de recruiter die er daarna naar kijkt. Allebei moeten ze in een paar seconden begrijpen waarom jij past." },
      { type: "h2", text: "Hoe leest en scoort een ATS je cv?" },
      { type: "p", text: "Het proces verloopt grofweg in drie stappen. Eerst parsen: het systeem haalt je cv uit elkaar en probeert te herkennen wat je naam is, wat je werkervaring is, welke opleiding je hebt en welke vaardigheden je noemt. Vervolgens structureren: die losse stukken worden in vaste velden geplaatst, zoals 'functietitel', 'werkgever', 'periode' en 'skills'. Tot slot scoren: het ATS vergelijkt jouw gegevens met de eisen uit de vacature en kent een match toe." },
      { type: "p", text: "Die match draait grotendeels om keywords. Een ATS zoekt naar specifieke woorden en zinsdelen die in de vacaturetekst staan, zoals functietitels, software, certificeringen en vaardigheden. Hoe beter jouw cv die termen letterlijk bevat, hoe hoger je score. Het systeem 'begrijpt' niet wat je bedoelt zoals een mens dat doet, het matcht vooral tekst." },
      { type: "h3", text: "Waarom exacte keywords zo belangrijk zijn" },
      { type: "p", text: "Veel ATS-instellingen matchen op exacte termen. Staat er in de vacature 'projectmanager', maar noem jij jezelf overal 'projectleider', dan kan het systeem die twee als verschillende dingen behandelen en mis je punten, ook al doe je precies hetzelfde werk. Hetzelfde geldt voor 'boekhouder' versus 'administratief medewerker' of 'developer' versus 'softwareontwikkelaar'." },
      { type: "p", text: "De oplossing is niet om te liegen, maar om aan te sluiten op de taal van de vacature. Neem de exacte functietitel en de belangrijkste vaktermen letterlijk over waar dat klopt met je ervaring. Twijfel je tussen twee varianten, noem dan allebei, bijvoorbeeld: 'Projectmanager (projectleider) bij...'. Zo dek je beide zoekopdrachten af." },
      { type: "quote", text: "Een ATS straft je niet voor wat je gedaan hebt, maar voor hoe je het opschrijft. Spreek de taal van de vacature en je score stijgt vanzelf." },
      { type: "h2", text: "Wat breekt het parsen van je cv?" },
      { type: "p", text: "Veel cv's komen niet door een ATS, niet omdat de kandidaat ongeschikt is, maar omdat de software de inhoud niet goed kan uitlezen. Dit zijn de meest voorkomende boosdoeners:" },
      { type: "ul", items: ["Tabellen: tekst in tabelcellen raakt vaak door elkaar of valt helemaal weg bij het parsen.", "Kolommen: een cv in twee kolommen wordt soms van links naar rechts gelezen, waardoor zinnen door elkaar lopen.", "Tekst in afbeeldingen: een ATS kan geen tekst lezen die als plaatje is opgeslagen, zoals een logo met je naam of een infographic met vaardigheden.", "Koppen en voetteksten: gegevens in de header of footer, zoals je telefoonnummer of e-mail, worden regelmatig genegeerd.", "Ongebruikelijke lettertypes en iconen: exotische fonts en symbolen kunnen verkeerd of als vreemde tekens worden ingelezen.", "Tekstvakken en grafische elementen: vormpjes, balken en kaders zorgen ervoor dat tekst buiten de normale leesvolgorde valt."] },
      { type: "p", text: "Het pijnlijke is dat juist de 'mooie', grafisch ontworpen cv-templates vaak het slechtst scoren. Een strak maar simpel opgemaakt cv komt er meestal veel beter doorheen dan een ontwerp vol kolommen en iconen." },
      { type: "h2", text: "Checklist: zo maak je je cv ATS-proof" },
      { type: "p", text: "Loop deze punten langs voordat je solliciteert. Ze kosten weinig tijd en vergroten je kans om de eerste filter te halen aanzienlijk." },
      { type: "ol", items: ["Gebruik een enkele kolom en een logische opbouw van boven naar beneden.", "Zet je contactgegevens gewoon in de hoofdtekst, niet in de header of footer.", "Lever je cv aan als tekstgebaseerde PDF of als Word-document, niet als afbeelding of gescand bestand.", "Gebruik standaard koppen die het systeem herkent, zoals 'Werkervaring', 'Opleiding' en 'Vaardigheden'.", "Neem de exacte functietitel en belangrijkste vaktermen uit de vacature letterlijk over waar ze kloppen.", "Vermijd tabellen, tekstvakken, kolommen en tekst in afbeeldingen.", "Kies een standaard, goed leesbaar lettertype zoals Arial, Calibri of Georgia.", "Schrijf functietitels en afkortingen voluit en voeg de afkorting toe, bijvoorbeeld 'Search Engine Optimization (SEO)'.", "Pas je cv aan per vacature: stem keywords en accenten af op die specifieke functie."] },
      { type: "p", text: "Met een cv-bouwer die rekening houdt met ATS-vriendelijke opmaak, zoals CVmaken.nu, hoef je je over de techniek nauwelijks druk te maken: de structuur is al ingericht op leesbaarheid voor zowel software als recruiters. Jij hoeft alleen nog de juiste keywords uit de vacature te verwerken." },
      { type: "p", text: "Onthoud tot slot: een ATS is geen vijand, maar een filter. Zodra je begrijpt hoe het leest en scoort, kun je je cv zo inrichten dat je sterke punten ook echt aankomen bij de mens die uiteindelijk beslist." },
    ],
    faq: [
      { q: "Hoeveel werkgevers gebruiken een ATS?", a: "In Nederland werkt naar schatting ruim 70 procent van de grote werkgevers met een Applicant Tracking System. Bij multinationals, banken, verzekeraars, grote retailers en de overheid is het vrijwel standaard. Ook steeds meer middelgrote bedrijven gebruiken zulke software om reacties te verzamelen en voor te selecteren." },
      { q: "Is een PDF of Word-bestand beter voor een ATS?", a: "Allebei kunnen prima werken, zolang het maar een tekstgebaseerd bestand is en geen afbeelding of scan. Een moderne ATS leest een nette PDF goed uit. Twijfel je, of vraagt de vacature expliciet om Word, lever dan een .docx aan. Vermijd in alle gevallen cv's die als plaatje zijn opgeslagen." },
      { q: "Moet ik keywords uit de vacature letterlijk overnemen?", a: "Ja, waar ze kloppen met je ervaring. Veel systemen matchen op exacte termen, dus 'projectmanager' en 'projectleider' kunnen anders worden behandeld. Neem de functietitel en belangrijkste vaktermen letterlijk over en noem eventueel beide varianten. Liegen heeft geen zin, want een recruiter checkt je cv daarna alsnog." },
      { q: "Waarom hoor ik niets terug, ook al ben ik geschikt?", a: "Vaak ligt het aan de opmaak. Tabellen, kolommen, tekst in afbeeldingen en gegevens in de header of footer kunnen ervoor zorgen dat een ATS je cv verkeerd of helemaal niet uitleest. Een simpel, eenkoloms cv met standaard koppen en de juiste keywords vergroot je kans om de eerste filter te passeren flink." },
    ],
  },
  {
    slug: "cv-zonder-werkervaring",
    title: "Van stage naar eerste baan: een cv zonder werkervaring",
    description:
      "Een cv zonder werkervaring schrijven? Ontdek wat wel meetelt en hoe je als starter met opleiding, skills en stages een sterk cv maakt.",
    excerpt:
      "Geen jarenlange loopbaan op je cv? Geen probleem. Zo bouw je als starter een overtuigend cv met je opleiding, stages, bijbanen en vaardigheden.",
    date: "2025-05-05",
    dateLabel: "5 mei 2025",
    readTime: "7 min",
    author: "CVmaken.nu Team",
    categories: ["Starters"],
    keywords: ["cv zonder werkervaring", "cv starter", "eerste baan cv", "cv schoolverlater", "cv afgestudeerd", "transferable skills", "cv stage", "profiel cv starter"],
    content: [
      { type: "p", text: "Net afgestudeerd of klaar met je opleiding, en dan die zin in de vacature: 'minimaal twee jaar werkervaring'. Frustrerend, want hoe krijg je ervaring als iedereen ervaring vraagt? Goed nieuws: je hebt waarschijnlijk veel meer relevante ervaring dan je denkt. In dit artikel laten we zien wat allemaal meetelt en hoe je als starter een cv schrijft dat indruk maakt, ook zonder jarenlange loopbaan." },
      { type: "h2", text: "Wat telt allemaal als ervaring?" },
      { type: "p", text: "Werkervaring is veel breder dan een vaste baan. Recruiters weten dat starters net beginnen en kijken vooral naar wat je hebt gedaan, geleerd en aangepakt. Deze zaken tellen allemaal mee en horen op je cv:" },
      { type: "ul", items: ["Bijbanen: vakkenvullen, horeca, callcenter of een baan bij de supermarkt laten zien dat je verantwoordelijkheid neemt en betrouwbaar bent.", "Stages: een stage is volwaardige werkervaring. Je hebt in een echte organisatie meegedraaid en concrete taken uitgevoerd.", "Studieprojecten: groepsopdrachten, een afstudeerproject of een onderzoek waarin je een echt probleem oploste tellen mee.", "Vrijwilligerswerk: of het nu een sportclub, een buurtinitiatief of een goed doel is, het toont inzet en sociale vaardigheden.", "Bestuurs- en commissiewerk: een functie in een studievereniging, medezeggenschapsraad of festivalcommissie laat leiderschap en organisatietalent zien.", "Eigen projecten: een webshop, een blog, freelance klusjes of het organiseren van een evenement zeggen veel over je initiatief."] },
      { type: "callout", title: "Ervaring is wat je hebt gedaan, niet alleen waar je betaald voor kreeg", text: "De meeste starters onderschatten zichzelf enorm. Een penningmeester van een studievereniging beheert een echte begroting. Een groepsproject vraagt om samenwerken, plannen en presenteren. Schrijf die ervaringen op alsof het werk was, want dat zijn het." },
      { type: "h2", text: "Begin met je opleiding en je vaardigheden" },
      { type: "p", text: "Bij een ervaren professional staat werkervaring bovenaan. Als starter draai je dat om: zet je opleiding bovenaan, want dat is je sterkste troef. Vermeld niet alleen je opleiding en school, maar ook relevante vakken, je afstudeeronderwerp, een hoog cijfer of een specialisatie die aansluit bij de functie." },
      { type: "p", text: "Direct daaronder, of zelfs ernaast, komt een blok met je vaardigheden. Denk aan software die je beheerst, talen die je spreekt en vakinhoudelijke kennis. Voor een starter is dit cruciaal, omdat het laat zien wat je nu al kunt, los van het aantal jaren ervaring." },
      { type: "h2", text: "Schrijf een sterk profiel als starter" },
      { type: "p", text: "Bovenaan je cv staat een kort profiel, vaak 'persoonlijk profiel' of 'over mij' genoemd. Voor een starter is dit goud waard: hier vertel je in drie of vier zinnen wie je bent, wat je net hebt afgerond en wat je komt brengen. Vermijd holle frasen als 'gemotiveerd en leergierig' zonder onderbouwing, en maak het concreet." },
      { type: "p", text: "Een sterk voorbeeld: 'Recent afgestudeerd hbo'er Commerciele Economie met een afstudeerstage in B2B-marketing bij een softwarebedrijf. Tijdens mijn studie organiseerde ik als bestuurslid het jaarlijkse netwerkevent voor 200 deelnemers. Ik zoek een startersfunctie waarin ik mijn analytische vaardigheden en mijn energie voor klantcontact kan inzetten.' Dit is specifiek, geeft bewijs en laat richting zien." },
      { type: "quote", text: "Een werkgever neemt geen starter aan voor wat je al hebt gedaan, maar voor wat je belooft te worden. Laat in je profiel zien waar je naartoe wilt." },
      { type: "h2", text: "Maak je transferable skills zichtbaar" },
      { type: "p", text: "Transferable skills zijn vaardigheden die je in de ene situatie hebt opgedaan en die je meeneemt naar een andere. Juist als starter zijn die je kapitaal. Het draait erom dat je laat zien dat je deze vaardigheden ergens echt hebt toegepast, niet dat je ze simpelweg opsomt." },
      { type: "ul", items: ["Samenwerken: bewezen in groepsprojecten, teamsporten of een bijbaan in de horeca.", "Plannen en organiseren: blijkt uit een commissie die je leidde of een evenement dat je opzette.", "Communiceren: presentaties tijdens je studie, klantcontact in een bijbaan of het schrijven van verslagen.", "Probleemoplossend vermogen: een lastige klantsituatie, een vastgelopen project of een onderzoeksvraag die je beantwoordde.", "Verantwoordelijkheid: het beheren van een kas, een rooster of een vaste taak waar anderen op rekenden."] },
      { type: "p", text: "Koppel elke vaardigheid aan een concreet voorbeeld. 'Sterk in samenwerken' zegt weinig. 'Werkte in een team van vijf aan een marktonderzoek en presenteerde de uitkomsten aan de opdrachtgever' zegt alles." },
      { type: "h2", text: "Hoe structureer je je cv als starter?" },
      { type: "p", text: "Een logische volgorde voor een startend cv ziet er zo uit. Houd het overzichtelijk op een, hooguit twee pagina's:" },
      { type: "ol", items: ["Contactgegevens: naam, telefoonnummer, e-mailadres en eventueel een LinkedIn-link.", "Persoonlijk profiel: drie of vier zinnen die je verhaal en je richting samenvatten.", "Opleiding: je hoogste of meest relevante opleiding bovenaan, met relevante vakken of je afstudeeronderwerp.", "Stages en werkervaring: stages, bijbanen en relevante klussen, met per onderdeel een paar concrete resultaten.", "Vaardigheden: software, talen en vakinhoudelijke kennis.", "Extra: bestuurs- en commissiewerk, vrijwilligerswerk, certificaten en relevante hobby's."] },
      { type: "p", text: "Beschrijf bij elke ervaring niet alleen wat je deed, maar ook wat het opleverde. Gebruik actieve werkwoorden zoals 'organiseerde', 'analyseerde', 'begeleidde' en 'verbeterde'. Een resultaat met een getal erbij, zoals 'verhoogde de opkomst van het event met 30 procent', valt extra op." },
      { type: "p", text: "Tot slot: laat je niet ontmoedigen door die '2 jaar ervaring' in een vacature. Dat is vaak een wens, geen harde eis. Met een cv dat je opleiding, stages, projecten en vaardigheden slim in beeld brengt, laat je zien dat je klaar bent voor die eerste echte baan. Met de starter-templates van CVmaken.nu staat de juiste structuur al voor je klaar, zodat jij je kunt richten op je verhaal." },
    ],
    faq: [
      { q: "Wat zet ik op mijn cv als ik nog nooit gewerkt heb?", a: "Veel meer dan je denkt. Stages, bijbanen, studieprojecten, vrijwilligerswerk en bestuurs- of commissiewerk tellen allemaal als ervaring. Zet je opleiding en vaardigheden bovenaan en beschrijf bij elke ervaring concreet wat je deed en wat het opleverde. Zo laat je zien wat je kunt, ook zonder een vaste baan in je verleden." },
      { q: "Moet ik mijn opleiding of mijn ervaring bovenaan zetten?", a: "Als starter zet je je opleiding bovenaan, want dat is je sterkste troef. Voeg relevante vakken, je afstudeeronderwerp of een specialisatie toe. Stages, bijbanen en projecten komen daaronder. Heb je later meer werkervaring, dan draai je deze volgorde om en zet je werkervaring bovenaan." },
      { q: "Wat zijn transferable skills en waarom zijn ze belangrijk?", a: "Transferable skills zijn vaardigheden die je in de ene situatie opdoet en meeneemt naar een andere, zoals samenwerken, plannen, communiceren en probleemoplossend vermogen. Voor starters zijn ze cruciaal, omdat ze laten zien wat je kunt los van het aantal jaren ervaring. Koppel elke vaardigheid altijd aan een concreet voorbeeld." },
      { q: "Moet ik solliciteren als ik niet aan de gevraagde jaren ervaring voldoe?", a: "Ja, zeker doen. De gevraagde jaren ervaring in een vacature zijn vaak een wens en geen harde eis, zeker bij startersfuncties. Als je het grootste deel van de taken aankunt en je motivatie en potentie kunt onderbouwen, is solliciteren bijna altijd de moeite waard." },
    ],
  },
  {
    slug: "sollicitatiegesprek-10-vragen",
    title: "Sollicitatiegesprek: 10 vragen die je moet voorbereiden",
    description:
      "Bereid je sollicitatiegesprek voor met de 10 meest gestelde vragen in Nederland. Ontdek wat de werkgever echt wil weten en hoe je sterk antwoordt.",
    excerpt:
      "De 10 sollicitatievragen die in vrijwel elk Nederlands gesprek voorbijkomen, met uitleg over wat de werkgever echt wil weten en hoe je je antwoord opbouwt.",
    date: "2025-04-28",
    dateLabel: "28 april 2025",
    readTime: "8 min",
    author: "CVmaken.nu Team",
    categories: ["Interview"],
    keywords: ["sollicitatiegesprek vragen", "sollicitatievragen voorbereiden", "STAR-methode", "veelgestelde sollicitatievragen", "sterke en zwakke punten", "sollicitatiegesprek tips", "salaris onderhandelen sollicitatie"],
    content: [
      { type: "p", text: "Een sollicitatiegesprek voelt vaak als een examen waarvan je de vragen niet kent. Toch valt dat in de praktijk reuze mee. Veruit de meeste Nederlandse werkgevers grijpen terug op een vaste set vragen, en die kennen we allemaal. Als je die tien klassiekers van tevoren doordenkt, stap je veel rustiger en zelfverzekerder de spreekkamer binnen. In dit artikel lopen we ze stuk voor stuk langs: wat de interviewer er echt mee wil achterhalen, en hoe je een antwoord opbouwt dat blijft hangen." },
      { type: "p", text: "Een rode draad door dit hele artikel is de STAR-methode. Daarmee beantwoord je gedragsvragen gestructureerd: je schetst de Situatie, de Taak die je had, de Actie die je ondernam en het Resultaat. Wie concrete voorbeelden geeft in plaats van algemene praatjes, scoort vrijwel altijd beter." },
      { type: "callout", title: "Tip vooraf", text: "Oefen je antwoorden hardop, niet alleen in je hoofd. Wat in gedachten logisch klinkt, struikelt soms hopeloos zodra je het uitspreekt. Neem jezelf desnoods op met je telefoon en luister terug." },
      { type: "h2", text: "1. Vertel eens iets over jezelf" },
      { type: "p", text: "Deze opener lijkt onschuldig, maar bepaalt vaak de eerste indruk. De interviewer wil geen levensverhaal horen, maar een kort, relevant overzicht van wie je professioneel bent en waarom je hier zit. Houd het bij zo'n twee minuten." },
      { type: "p", text: "Een handige opbouw is heden, verleden, toekomst: vertel kort wat je nu doet, hoe je daar gekomen bent, en wat je nu zoekt. Sluit af met een bruggetje naar deze functie. Vermijd je hobby's en privédetails, tenzij ze echt relevant zijn." },
      { type: "h2", text: "2. Wat zijn je sterke punten?" },
      { type: "p", text: "Hier checkt de werkgever of jouw kwaliteiten aansluiten bij de functie. Het is geen uitnodiging om alles op te sommen wat je goed kunt. Kies twee of drie sterke punten die direct relevant zijn voor de baan, en onderbouw elk met een kort voorbeeld." },
      { type: "p", text: "Zeg dus niet alleen dat je analytisch bent, maar laat met een korte STAR-mini zien wanneer dat verschil maakte. Een bewering zonder bewijs blijft een loze claim." },
      { type: "h2", text: "3. Wat zijn je zwakke punten?" },
      { type: "p", text: "De gevreesde klassieker. De interviewer test je zelfkennis en eerlijkheid, niet of je een perfect mens bent. Het verkapte sterke punt ('ik ben te perfectionistisch') prikken ze meteen door en komt vaak goedkoop over." },
      { type: "p", text: "Noem een echt ontwikkelpunt dat niet de kern van de functie raakt, en vooral: vertel wat je eraan doet. De groei is belangrijker dan het gebrek zelf." },
      { type: "quote", text: "Een eerlijk zwak punt met een concreet verbeterplan maakt vaak meer indruk dan tien gladde sterke punten." },
      { type: "h2", text: "4. Waarom wil je hier werken?" },
      { type: "p", text: "Met deze vraag wordt getoetst of je je hebt verdiept in het bedrijf, of dat je gewoon overal solliciteert. Een algemeen antwoord over 'een mooi bedrijf met fijne sfeer' valt door de mand." },
      { type: "p", text: "Bereid je voor door de website, recente nieuwsberichten en de vacaturetekst goed te lezen. Verbind iets concreets aan het bedrijf, zoals een product, een waarde of een ambitie, aan jouw eigen drijfveren." },
      { type: "h2", text: "5. Waarom verlaat je je huidige baan?" },
      { type: "p", text: "De werkgever wil hier vooral geen alarmbellen horen. Spreek nooit negatief over je huidige of vorige werkgever, hoe verleidelijk dat ook is. Klagen schaadt vooral jouw eigen imago." },
      { type: "p", text: "Formuleer je reden positief en vooruitkijkend: je zoekt meer verantwoordelijkheid, een nieuwe uitdaging of groeimogelijkheden die je huidige plek niet meer biedt. Richt je op wat je toe wilt, niet op wat je ontvlucht." },
      { type: "h2", text: "6. Waar zie je jezelf over 5 jaar?" },
      { type: "p", text: "Deze vraag peilt je ambitie en of je waarschijnlijk een tijdje blijft. Werkgevers investeren liever in iemand die niet binnen een jaar weer vertrekt." },
      { type: "p", text: "Schets een realistische groeirichting die logisch aansluit op de functie. Je hoeft geen exact carrièrepad uit te tekenen, maar laat zien dat je nadenkt over ontwikkeling en dat die ontwikkeling past binnen dit bedrijf." },
      { type: "h2", text: "7. Wat zijn je salariswensen?" },
      { type: "p", text: "In Nederland komt de salarisvraag vaak pas later in het proces, maar wees voorbereid. De werkgever wil weten of jullie verwachtingen matchen. Een te laag bedrag noemen kost je geld, een te hoog bedrag kan je uit de race halen." },
      { type: "p", text: "Doe vooraf onderzoek naar marktconforme salarissen voor de functie, sector en regio. Noem bij voorkeur een bandbreedte en koppel die aan je ervaring. Vraag bij twijfel gerust naar de salarisindicatie die zij in gedachten hebben." },
      { type: "callout", title: "Onderhandel rustig", text: "Salaris is meer dan het brutobedrag. Denk ook aan vakantiedagen, thuiswerkregeling, reiskosten, pensioen en opleidingsbudget. Een totaalpakket biedt veel meer ruimte om te onderhandelen." },
      { type: "h2", text: "8. Hoe ga je om met stress of tegenslag?" },
      { type: "p", text: "Een typische gedragsvraag, ideaal voor de STAR-methode. De interviewer wil weten of je onder druk overeind blijft en hoe je problemen aanpakt." },
      { type: "p", text: "Kies een concreet voorbeeld van een drukke of lastige periode. Beschrijf de situatie en je taak, leg uit welke acties je ondernam om grip te houden, en sluit af met het resultaat. Laat zien dat je leert van tegenslag." },
      { type: "h2", text: "9. Kun je een voorbeeld geven van een conflict en hoe je dat oploste?" },
      { type: "p", text: "Hiermee toetst de werkgever je samenwerking en communicatie. Doe niet alsof je nooit een meningsverschil hebt gehad, want dat gelooft niemand." },
      { type: "p", text: "Gebruik opnieuw STAR. Beschrijf een zakelijk conflict zonder de ander zwart te maken, focus op hoe je het gesprek aanging en tot een oplossing kwam. De nadruk ligt op jouw houding, niet op wie er gelijk had." },
      { type: "h2", text: "10. Heb je nog vragen voor ons?" },
      { type: "p", text: "Bijna elk gesprek eindigt hiermee, en 'nee' is echt het verkeerde antwoord. Het signaleert desinteresse. Goede vragen laten zien dat je betrokken bent en serieus nadenkt over de rol." },
      { type: "p", text: "Bereid drie tot vijf vragen voor, want sommige worden al tijdens het gesprek beantwoord. Denk aan vragen als deze:" },
      { type: "ul", items: ["Hoe ziet een gemiddelde werkdag of werkweek in deze functie eruit?", "Wat zijn de belangrijkste uitdagingen voor het team het komende jaar?", "Hoe wordt succes in deze rol gemeten?", "Hoe ziet het vervolg van de sollicitatieprocedure eruit?", "Wat waardeer jij zelf het meest aan het werken hier?"] },
      { type: "h2", text: "Tot slot" },
      { type: "p", text: "Voorbereiding is geen garantie, maar het scheelt enorm in je rust en zelfvertrouwen. Schrijf je antwoorden niet woord voor woord uit, want dan klink je als een afgedraaide plaat. Werk in plaats daarvan met kernpunten en concrete voorbeelden, zodat je flexibel blijft. Combineer dit met een sterk, op de functie afgestemd cv, en je staat er goed op. Succes met je gesprek." },
    ],
    faq: [
      { q: "Hoe lang van tevoren moet ik me voorbereiden op een sollicitatiegesprek?", a: "Reken op minimaal twee tot drie uur verspreid over een paar dagen. Zo heb je tijd om het bedrijf te onderzoeken, je antwoorden op de belangrijkste vragen te doordenken en ze een keer hardop te oefenen. Verspreid oefenen werkt beter dan alles op het laatste moment." },
      { q: "Wat is de STAR-methode precies?", a: "STAR staat voor Situatie, Taak, Actie en Resultaat. Je beantwoordt een gedragsvraag door eerst de context te schetsen, dan je taak, vervolgens wat je concreet deed en tot slot wat het opleverde. Zo geef je een gestructureerd en geloofwaardig antwoord met bewijs in plaats van algemene beweringen." },
      { q: "Moet ik mijn salariswens noemen of vragen naar de bandbreedte?", a: "Beide kan, maar onderzoek altijd eerst marktconforme salarissen voor de functie, sector en regio. Noem bij voorkeur een onderbouwde bandbreedte op basis van je ervaring. Twijfel je, vraag dan welk budget de werkgever voor de rol in gedachten heeft, dan voorkom je dat je jezelf te laag of te hoog inschaalt." },
      { q: "Wat als ik geen vragen heb aan het einde van het gesprek?", a: "Bereid altijd drie tot vijf vragen voor, want geen vragen stellen komt over als desinteresse. Goede onderwerpen zijn de dagelijkse praktijk van de functie, de uitdagingen van het team, hoe succes wordt gemeten en het vervolg van de procedure." },
    ],
  },
  {
    slug: "linkedin-vs-cv",
    title: "LinkedIn vs cv: wat schrijf je waar?",
    description:
      "LinkedIn vs cv: ontdek het verschil, waarom kopiëren een fout is en welke informatie waar hoort. Praktische tips voor de Nederlandse arbeidsmarkt.",
    excerpt:
      "Je LinkedIn-profiel en je cv hebben verschillende lezers en doelen. Dit artikel laat zien wat waar hoort, en hoe je beide consistent houdt zonder te dubbelen.",
    date: "2025-04-18",
    dateLabel: "18 april 2025",
    readTime: "5 min",
    author: "CVmaken.nu Team",
    categories: ["LinkedIn"],
    keywords: ["LinkedIn vs cv", "verschil LinkedIn en cv", "LinkedIn profiel optimaliseren", "LinkedIn headline", "cv afstemmen op vacature", "LinkedIn about sectie", "solliciteren LinkedIn"],
    content: [
      { type: "p", text: "'Ik heb mijn cv gewoon op LinkedIn gezet, klaar.' Het klinkt efficiënt, maar het is een gemiste kans. Je cv en je LinkedIn-profiel lijken op het eerste gezicht op elkaar, maar ze doen heel verschillend werk. Wie ze door elkaar haalt, krijgt twee halfslachtige documenten in plaats van twee sterke. In dit artikel leggen we uit waar het verschil zit, wat waar hoort en hoe je ze consistent houdt zonder eindeloos te kopiëren en plakken." },
      { type: "h2", text: "Verschillende lezers, verschillende doelen" },
      { type: "p", text: "Het belangrijkste verschil zit in de lezer en het doel. Je cv schrijf je voor één specifieke persoon, de recruiter of hiring manager van één specifieke vacature. Het doel is concreet: uitgenodigd worden voor dat ene gesprek. Daarom is een goed cv kort, gericht en helemaal afgestemd op die functie." },
      { type: "p", text: "Je LinkedIn-profiel staat juist altijd online, voor een breed en onbekend publiek: recruiters die actief zoeken, oud-collega's, klanten, leveranciers en mensen uit je netwerk. Het doel is breder: vindbaar en interessant zijn voor kansen die je nu nog niet kent. Hier mag je dus een wat completer en persoonlijker verhaal vertellen." },
      { type: "callout", title: "De kern in één zin", text: "Je cv is een scherpgeslepen pijl op één doel. Je LinkedIn-profiel is een vitrine die altijd open is voor iedereen die langsloopt." },
      { type: "h2", text: "Waarom kopiëren een fout is" },
      { type: "p", text: "Je cv letterlijk overzetten naar LinkedIn werkt om twee redenen niet goed. Ten eerste is een cv geschreven voor één vacature, terwijl LinkedIn voor alle mogelijke kansen tegelijk moet werken. De scherpe focus die je cv sterk maakt, maakt je profiel juist te smal." },
      { type: "p", text: "Ten tweede is een cv kort en zakelijk, met opsommingen en zonder veel toon. Dat leest op een levend platform als LinkedIn droog en afstandelijk. LinkedIn vraagt om een persoonlijkere stem, eerste persoon, en ruimte voor je verhaal en motivatie." },
      { type: "h2", text: "Wat LinkedIn beter doet" },
      { type: "p", text: "Op een paar punten is LinkedIn duidelijk in het voordeel. Speel die troeven uit in plaats van je profiel te behandelen als een statisch document." },
      { type: "ul", items: ["Netwerk en zichtbaarheid: recruiters zoeken er actief, dus je wordt gevonden zonder dat je solliciteert.", "Zoekwoorden: LinkedIn werkt als zoekmachine, dus relevante vaktermen en functietitels in je profiel vergroten je vindbaarheid.", "Aanbevelingen en skill-endorsements: anderen bevestigen jouw kwaliteiten, iets wat in een cv niet kan.", "Ruimte voor verhaal: je mag uitweiden over je drijfveren, projecten en visie, zonder de strakke lengtegrens van een cv.", "Altijd actueel: één update is meteen zichtbaar voor je hele netwerk."] },
      { type: "h2", text: "Wat het cv beter doet" },
      { type: "p", text: "Het cv blijft onmisbaar, juist omdat het iets kan wat LinkedIn niet kan: volledig op maat zijn." },
      { type: "ul", items: ["Maatwerk: je stemt elk cv af op één vacature, met precies de juiste accenten en zoekwoorden uit de vacaturetekst.", "Beknoptheid: één tot twee pagina's dwingen je tot de essentie, wat recruiters waarderen.", "Controle over layout: jij bepaalt de volgorde, opmaak en wat als eerste opvalt.", "Formeel document: het hoort bij de officiële sollicitatie en is vaak vereist in het proces."] },
      { type: "h2", text: "Consistent houden zonder te dubbelen" },
      { type: "p", text: "Je profiel en cv moeten kloppen met elkaar, want recruiters checken beide. Verschillende functietitels of data wekken wantrouwen. Consistentie betekent echter niet dat alles identiek hoeft te zijn." },
      { type: "ol", items: ["Houd harde feiten gelijk: werkgevers, functietitels, periodes en opleidingen moeten op beide overeenkomen.", "Varieer de toon: schrijf je cv zakelijk en je LinkedIn-profiel persoonlijker en in de eerste persoon.", "Werk vanuit één bron: noteer je carrièregegevens op één plek en stem cv en profiel daarop af, zodat updates nooit ergens blijven hangen.", "Laat ze elkaar aanvullen: gebruik LinkedIn voor context en verhaal, en je cv voor de gerichte samenvatting per vacature."] },
      { type: "h2", text: "De headline en de about-sectie" },
      { type: "p", text: "Twee onderdelen maken het verschil op LinkedIn, en juist die worden vaak verwaarloosd. Je headline is de regel onder je naam. Veel mensen zetten daar alleen hun functietitel neer, maar dit is kostbare ruimte vol zoekwoorden. Combineer je rol met je vakgebied en eventueel een specialisme, bijvoorbeeld 'Marketeer | Specialist in B2B contentstrategie en SEO'." },
      { type: "p", text: "De about-sectie, het stuk 'Info', is je kans op een kort en pakkend verhaal in de eerste persoon. Vertel wie je bent, waar je goed in bent en wat je drijft, in een paar leesbare alinea's. Dit is precies het soort persoonlijke tekst die niet in een cv past, maar op LinkedIn het verschil maakt." },
      { type: "callout", title: "Snelle winst", text: "Verwerk de belangrijkste vaktermen uit jouw vakgebied in je headline en about-sectie. LinkedIn gebruikt die woorden om je te matchen met zoekopdrachten van recruiters." },
      { type: "h2", text: "Tot slot" },
      { type: "p", text: "Zie je cv en LinkedIn als een team, niet als kopieën van elkaar. Je cv overtuigt één recruiter voor één baan, je LinkedIn-profiel trekt kansen aan die je nog niet kent. Houd de feiten gelijk, varieer de toon en benut wat elk platform het beste doet. Dan werken ze samen in plaats van langs elkaar heen." },
    ],
    faq: [
      { q: "Kan ik mijn cv gewoon kopiëren naar mijn LinkedIn-profiel?", a: "Beter van niet. Een cv is afgestemd op één specifieke vacature en kort en zakelijk geschreven, terwijl LinkedIn voor een breed publiek en alle mogelijke kansen moet werken. Kopiëren levert een te smal en droog profiel op. Houd de feiten gelijk, maar schrijf je profiel persoonlijker en breder." },
      { q: "Wat is het belangrijkste verschil tussen LinkedIn en een cv?", a: "De lezer en het doel. Je cv schrijf je voor één recruiter en één vacature, gericht op die ene uitnodiging. Je LinkedIn-profiel staat altijd online voor een breed publiek en is bedoeld om vindbaar en interessant te zijn voor kansen die je nog niet kent." },
      { q: "Hoe houd ik mijn cv en LinkedIn-profiel consistent?", a: "Zorg dat de harde feiten overeenkomen: werkgevers, functietitels, periodes en opleidingen moeten op beide gelijk zijn, want recruiters checken vaak allebei. Varieer wel de toon en werk vanuit één bron met je carrièregegevens, zodat updates nergens blijven hangen." },
      { q: "Wat moet er in mijn LinkedIn-headline staan?", a: "Niet alleen je functietitel. De headline is kostbare ruimte voor zoekwoorden waarmee recruiters je vinden. Combineer je rol met je vakgebied en eventueel een specialisme, bijvoorbeeld 'Marketeer | Specialist in B2B contentstrategie en SEO'." },
    ],
  },
];

export function getAllPosts(): BlogPost[] {
  return BLOG_POSTS;
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}

export function getFeaturedPost(): BlogPost {
  return BLOG_POSTS[0];
}

export function getOtherPosts(): BlogPost[] {
  return BLOG_POSTS.slice(1);
}

export function getRelatedPosts(slug: string, limit = 3): BlogPost[] {
  const current = getPostBySlug(slug);
  if (!current) return BLOG_POSTS.slice(0, limit);
  const scored = BLOG_POSTS.filter((p) => p.slug !== slug).map((p) => ({
    post: p,
    score: p.categories.filter((c) => current.categories.includes(c)).length,
  }));
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((s) => s.post);
}
