import { type ResumeDocument } from "./model";

export const EXAMPLE_RESUME: ResumeDocument = {
  version: 1,
  personalDetails: {
    firstName: "Sophie",
    lastName: "de Vries",
    professionalTitle: "Marketing Manager",
    email: "sophie.devries@voorbeeld.nl",
    phone: "06 12 34 56 78",
    city: "Amsterdam",
    linkedinUrl: "linkedin.com/in/sophie-devries",
    websiteUrl: "",
    photoUrl: "",
  },
  profileSummary:
    "Resultaatgerichte marketing manager met 6 jaar ervaring in digitale campagnes, contentstrategie en merkpositionering. Sterk in het verbinden van data-inzichten met creatieve campagnes die daadwerkelijk conversies opleveren. Gewend aan snel schakelen in dynamische omgevingen en het aansturen van multidisciplinaire teams.",
  workExperience: [
    {
      id: "we-1",
      jobTitle: "Marketing Manager",
      company: "TechStart BV",
      location: "Amsterdam",
      startDate: "jan 2022",
      endDate: "",
      isCurrent: true,
      bullets: [
        "Leidde rebranding die online zichtbaarheid met 40% verhoogde binnen 6 maanden",
        "Beheerde jaarlijks marketingbudget van €250.000 en rapporteerde aan de directie",
        "Coördineerde team van 4 marketeers en 2 externe creatieve bureaus",
        "Ontwikkelde en lanceerde leadgeneratie-campagnes met gemiddeld 22% conversieratio",
      ],
    },
    {
      id: "we-2",
      jobTitle: "Content Strateeg",
      company: "MediaGroup Nederland",
      location: "Utrecht",
      startDate: "mrt 2019",
      endDate: "dec 2021",
      isCurrent: false,
      bullets: [
        "Ontwikkelde contentstrategie voor 15+ B2B-klanten in uiteenlopende sectoren",
        "Verhoogde organisch websiteverkeer met gemiddeld 65% via SEO-gedreven content",
        "Produceerde maandelijks 20+ artikelen, whitepapers en social content",
      ],
    },
    {
      id: "we-3",
      jobTitle: "Junior Marketeer",
      company: "Bureau Creatief",
      location: "Rotterdam",
      startDate: "sep 2017",
      endDate: "feb 2019",
      isCurrent: false,
      bullets: [
        "Ondersteunde bij opzet en uitvoering van social-mediacampagnes",
        "Analyseerde campagneprestaties met Google Analytics en stelde rapportages op",
      ],
    },
  ],
  education: [
    {
      id: "edu-1",
      institution: "Universiteit van Amsterdam",
      degree: "Master",
      fieldOfStudy: "Communicatiewetenschap",
      location: "Amsterdam",
      startDate: "sep 2015",
      endDate: "jul 2017",
      isCurrent: false,
      description: "Afstudeerrichting: Persuasieve Communicatie. Scriptie over social-proof in online advertenties.",
    },
    {
      id: "edu-2",
      institution: "Hogeschool Rotterdam",
      degree: "Bachelor",
      fieldOfStudy: "Commerciële Economie",
      location: "Rotterdam",
      startDate: "sep 2011",
      endDate: "jul 2015",
      isCurrent: false,
      description: "",
    },
  ],
  skills: [
    "Google Analytics 4",
    "SEO / SEA",
    "HubSpot CRM",
    "Canva & Adobe Suite",
    "Copywriting",
    "A/B-testen",
    "Projectmanagement",
  ],
  languages: [
    { id: "lang-1", name: "Nederlands", level: "Moedertaal" },
    { id: "lang-2", name: "Engels", level: "C1" },
    { id: "lang-3", name: "Duits", level: "B1" },
  ],
  certificates: [
    { id: "cert-1", name: "Google Analytics Certificering", description: "Google, 2024" },
  ],
  courses: [
    { id: "course-1", name: "Growth Hacking Bootcamp", description: "Emerce Academy, 2023" },
  ],
  interests: ["Hardlopen", "Reizen", "Podcasts over bedrijfsstrategie"],
  references: [],
  customSections: [],
};
