import type { RichSection } from "./types";

export type Enrichment = {
  salary?: { range: string; note: string };
  recruiterSkills?: string[];
  sections?: RichSection[];
  profileExamples?: string[];
  relatedRoles?: string[];
  faq?: { q: string; a: string }[];
};

/**
 * Rich, search-query-oriented content per cv-example slug. Merged into the
 * detail page at render time so examples.ts stays focused on the CV data.
 */
export const CV_ENRICHMENT: Record<string, Enrichment> = {
  "administratief-medewerker": {
    salary: { range: "EUR 2.300 - 3.300 bruto per maand", note: "Het exacte salaris hangt af van je werkervaring, opleidingsniveau (mbo of hbo), de branche en de regio, waarbij administratief medewerkers in de Randstad en in de financiele sector doorgaans bovengemiddeld verdienen." },
    recruiterSkills: ["Microsoft Office (Word, Excel, Outlook)", "Boekhoudsoftware (Exact, AFAS, Twinfield)", "Gegevensinvoer en datakwaliteit", "Facturatie en debiteurenbeheer", "Agendabeheer en planning", "Klantcontact en telefonische vaardigheden", "Nauwkeurigheid en oog voor detail", "Dossierbeheer en archivering", "Notuleren", "Typevaardigheid (300+ aanslagen per minuut)", "Zelfstandig werken", "Vertrouwelijkheid en discretie"],
    sections: [
      { heading: "Hoeveel verdient een administratief medewerker?", body: ["Een administratief medewerker in Nederland verdient in 2025 gemiddeld tussen de EUR 2.300 en EUR 3.300 bruto per maand bij een fulltime dienstverband van 36 tot 40 uur. Starters zonder relevante ervaring beginnen vaak rond de EUR 2.300 tot EUR 2.500, terwijl ervaren administratief medewerkers met vijf jaar of meer ervaring en specialistische kennis van boekhoudsoftware kunnen doorgroeien naar EUR 3.000 tot EUR 3.500.", "De branche heeft een grote invloed op je salaris. Binnen de zakelijke dienstverlening, de financiele sector en bij grotere organisaties liggen de salarissen structureel hoger dan in de zorg, het onderwijs of bij kleine mkb-bedrijven. Ook de cao die van toepassing is bepaalt veel: de cao voor de detailhandel of zorg kent andere schalen dan de cao Metalektro of de bankensector.", "Naast je vaste salaris zijn secundaire arbeidsvoorwaarden belangrijk om mee te wegen. Denk aan een dertiende maand, reiskostenvergoeding, thuiswerkvergoeding en opleidingsbudget. Bij het onderhandelen helpt het om concrete cijfers te noemen, zoals het aantal facturen dat je per maand verwerkt of de software waarin je gecertificeerd bent."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een administratief medewerker?", body: ["Werkgevers zoeken bij een administratief medewerker vooral naar nauwkeurigheid, betrouwbaarheid en sterke softwarevaardigheden. Microsoft Office, en dan met name Excel, is vrijwel altijd een harde eis. Wie formules zoals VERT.ZOEKEN, draaitabellen en voorwaardelijke opmaak beheerst, onderscheidt zich direct van andere kandidaten. Vermeld daarom in je cv concreet welke functies je gebruikt in plaats van alleen 'goede Excel-kennis'.", "Daarnaast is ervaring met specifieke boekhoud- en ERP-pakketten zoals Exact, AFAS, Twinfield of SAP zeer gewild. Recruiters scannen cv's vaak op deze exacte termen, dus neem ze letterlijk over als je ermee hebt gewerkt. Ook softskills als communicatief vermogen, stressbestendigheid bij piekmomenten zoals maandafsluitingen, en het kunnen schakelen tussen verschillende taken wegen zwaar mee.", "Tot slot waarderen werkgevers blijk van zelfstandigheid en procesverbetering. Wie kan aantonen dat hij een archiveringssysteem heeft opgezet, een handmatig proces heeft geautomatiseerd of de doorlooptijd van facturatie heeft verkort, laat zien dat hij meer biedt dan routinewerk. Maak deze prestaties meetbaar met percentages of tijdsbesparingen."] },
      { heading: "Veelgemaakte fouten op een administratief medewerker-cv", body: ["De meest voorkomende fout is een cv vol vage standaardzinnen zoals 'verantwoordelijk voor diverse administratieve taken'. Dit zegt een recruiter niets. Beschrijf in plaats daarvan concreet wat je deed: 'verwerkte gemiddeld 200 inkoopfacturen per week in Exact Online en bewaakte de betalingstermijnen'. Juist bij administratieve functies, waar nauwkeurigheid de kern is, valt een onnauwkeurig geschreven cv extra negatief op.", "Een tweede valkuil zijn spelfouten en een rommelige opmaak. Voor een functie waarin precisie en presentatie tellen, is een cv met typefouten of inconsistente datums een directe afknapper. Laat je cv altijd door iemand anders nalezen en houd de opmaak strak en consistent, met dezelfde lettertypes, uitlijning en datumnotatie.", "Ten derde vergeten veel kandidaten hun software- en systeemkennis expliciet te benoemen. Omdat veel werkgevers cv's eerst door een ATS-systeem laten filteren op trefwoorden, mis je sollicitaties als je de exacte pakketnamen niet vermeldt. Neem een aparte kopje 'Vaardigheden' of 'Systemen' op met alle relevante software."] },
      { heading: "Welke opleiding en certificaten heb je nodig als administratief medewerker?", body: ["Voor de meeste administratieve functies is een mbo-opleiding op niveau 3 of 4 in een richting als Bedrijfsadministratie, Secretarieel of Financieel administratief medewerker de standaard. Voor functies met meer verantwoordelijkheid, zoals administratief medewerker bij een accountantskantoor of op een financiele afdeling, wordt soms een hbo-werk-en-denkniveau gevraagd.", "Aanvullende certificaten kunnen je cv flink versterken. Denk aan een Praktijkdiploma Boekhouden (PDB), een Moderne Bedrijfsadministratie (MBA-diploma) of officiele Microsoft Office Specialist-certificeringen. Ook een certificaat voor specifieke software, zoals een Exact- of AFAS-training, maakt je direct inzetbaar en aantrekkelijker.", "Heb je geen diploma in de richting maar wel relevante ervaring? Benadruk dan je werkervaring en de systemen die je beheerst. Veel werkgevers hechten in de praktijk meer waarde aan aantoonbare ervaring met hun processen dan aan een exact passend diploma. Cursussen die je via een vorige werkgever volgde zijn ook het vermelden waard."] },
    ],
    profileExamples: ["Recent afgestudeerd administratief medewerker (mbo-4 Bedrijfsadministratie) met een sterke affiniteit voor cijfers en systemen. Tijdens mijn stage van zes maanden verwerkte ik zelfstandig inkoopfacturen in Exact Online en hield ik de debiteurenadministratie bij. Ik werk nauwkeurig, leer snel nieuwe software en zoek een functie waarin ik mij verder kan ontwikkelen binnen de financiele administratie.", "Ervaren administratief medewerker met ruim zeven jaar ervaring binnen het mkb. Ik verwerk gemiddeld 250 facturen per week, beheer de crediteuren- en debiteurenadministratie en ondersteun bij de maandafsluiting in AFAS. Collega's omschrijven mij als nauwkeurig, proactief en stressbestendig, ook tijdens drukke periodes. Ik ben op zoek naar een veelzijdige administratieve rol met ruimte voor procesverbetering.", "Allround administratief specialist met twaalf jaar ervaring en diepgaande kennis van Exact, Twinfield en geavanceerd Excel. Ik heb meerdere keren een handmatig facturatieproces geautomatiseerd, wat de doorlooptijd met 40 procent verkortte. Naast de dagelijkse administratie fungeer ik als aanspreekpunt voor de accountant en begeleid ik nieuwe collega's. Ik zoek een rol waarin ik mijn kennis kan inzetten om processen verder te professionaliseren."],
    relatedRoles: ["accountant", "logistiek-medewerker", "hr-adviseur"],
    faq: [
      { q: "Is ervaring met Excel verplicht voor een administratief medewerker?", a: "In vrijwel alle administratieve functies is Excel een basisvereiste. Werkgevers verwachten minimaal dat je kunt werken met filters, sorteren en eenvoudige formules. Voor functies op de financiele afdeling worden draaitabellen en functies zoals VERT.ZOEKEN vaak als pluspunt of zelfs als eis genoemd." },
      { q: "Kan ik administratief medewerker worden zonder diploma?", a: "Het kan, maar het is lastiger. Veel vacatures vragen minimaal mbo-niveau 3 of 4. Heb je geen relevant diploma, dan vergroot je je kansen met aantoonbare werkervaring, een afgeronde cursus boekhouden zoals PDB, of certificeringen in software als Exact of AFAS." },
      { q: "Wat is het verschil tussen een administratief medewerker en een secretaresse?", a: "Een administratief medewerker richt zich vooral op het verwerken van gegevens, facturen en dossiers, terwijl een secretaresse meer ondersteunend werkt voor een persoon of team met agendabeheer, correspondentie en organisatie. De rollen overlappen, maar bij administratie ligt de nadruk op cijfers en systemen en bij de secretaresse op ondersteuning en planning." },
      { q: "Welke trefwoorden moet ik in mijn cv zetten om door het ATS-systeem te komen?", a: "Neem de exacte software- en pakketnamen op die in de vacature staan, zoals Exact, AFAS, Twinfield, SAP of Microsoft Office. Voeg ook concrete taken toe zoals facturatie, debiteurenbeheer, crediteurenadministratie en gegevensinvoer. ATS-systemen filteren op deze letterlijke termen, dus stem je cv per vacature af." },
    ],
  },
  "software-engineer": {
    salary: { range: "EUR 3.500 - 5.500 bruto per maand", note: "Het salaris wordt sterk bepaald door je senioriteit, de programmeertalen en frameworks die je beheerst, de sector (fintech en scale-ups betalen meer) en of je in de Randstad werkt, waar de tarieven duidelijk hoger liggen." },
    recruiterSkills: ["Python, Java of C#", "JavaScript en TypeScript", "React, Angular of Vue", "Node.js en REST API's", "SQL en NoSQL databases", "Git en versiebeheer", "CI/CD pipelines", "Docker en Kubernetes", "Cloud (AWS, Azure of GCP)", "Agile en Scrum", "Unit testing en TDD", "Microservices-architectuur"],
    sections: [
      { heading: "Hoeveel verdient een software engineer?", body: ["Een software engineer in Nederland verdient in 2025 gemiddeld tussen de EUR 3.500 en EUR 5.500 bruto per maand. Een junior of medior developer met enkele jaren ervaring zit doorgaans rond de EUR 3.500 tot EUR 4.500, terwijl een senior software engineer met diepgaande kennis en architectuurverantwoordelijkheid kan doorgroeien naar EUR 5.500 tot EUR 7.000 of meer.", "De gevraagde technologie heeft veel invloed op je salaris. Engineers met schaarse of specialistische kennis, zoals cloud-architectuur, machine learning, Rust of Go, verdienen vaak bovengemiddeld. Ook de sector telt mee: fintech, scale-ups en gespecialiseerde productbedrijven betalen structureel beter dan traditionele organisaties of de publieke sector.", "Veel software engineers werken als zzp'er of via detachering tegen uurtarieven van EUR 65 tot EUR 110 of hoger. Houd er bij het vergelijken van loondienst en zelfstandig ondernemerschap rekening mee dat secundaire voorwaarden zoals pensioen, opleidingsbudget, een laptop naar keuze en de aandelen- of bonusregeling bij scale-ups een aanzienlijk deel van het totale pakket vormen."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een software engineer?", body: ["Werkgevers zoeken in de eerste plaats naar aantoonbare beheersing van relevante programmeertalen en frameworks. Welke dat zijn hangt af van de stack: voor backend gaat het vaak om Java, C#, Python of Node.js, voor frontend om React, Angular of Vue met TypeScript. Vermeld in je cv niet alleen welke talen je kent, maar ook op welk niveau en in welke projecten je ze hebt toegepast.", "Naast pure programmeerkennis is ervaring met moderne ontwikkelpraktijken doorslaggevend. Denk aan versiebeheer met Git, geautomatiseerd testen, CI/CD-pipelines en containerisatie met Docker en Kubernetes. Cloudkennis van AWS, Azure of GCP is inmiddels bij veel functies een vereiste. Recruiters scannen cv's letterlijk op deze technologieen, dus gebruik de gangbare benamingen.", "Tot slot wegen softskills en werkwijze zwaar mee. Engineers werken vrijwel altijd in Agile- of Scrum-teams, dus ervaring met samenwerken, code reviews en het opleveren in sprints is belangrijk. Werkgevers letten ook op probleemoplossend vermogen, communicatie met niet-technische stakeholders en de bereidheid om continu nieuwe technologie te leren."] },
      { heading: "Veelgemaakte fouten op een software engineer-cv", body: ["Een veelgemaakte fout is het opsommen van tientallen technologieen zonder context. Een lange lijst met buzzwords maakt het voor een recruiter onmogelijk in te schatten waar je echt goed in bent. Geef per technologie aan op welk niveau je werkt en koppel ze aan concrete projecten en resultaten, bijvoorbeeld 'bouwde een microservice in Go die de responstijd met 60 procent verkortte'.", "Een tweede fout is het ontbreken van meetbare impact. Veel engineers beschrijven wat ze technisch deden, maar niet wat het opleverde. Werkgevers willen weten welk probleem je hebt opgelost en wat het effect was: minder bugs, snellere deploys, hogere uptime of een betere gebruikerservaring. Vertaal je werk naar businesswaarde.", "Ten derde vergeten veel kandidaten een link naar hun GitHub, portfolio of relevante open-sourcebijdragen op te nemen. Voor een technische functie is aantoonbare code vaak overtuigender dan welke omschrijving dan ook. Zorg dat de gelinkte projecten representatief en opgeruimd zijn, met een duidelijke README."] },
      { heading: "Hoe schrijf je een sterke profieltekst als software engineer?", body: ["De profieltekst bovenaan je cv is je elevator pitch. In drie tot vier zinnen maak je duidelijk wie je bent, in welke stack je sterk bent en wat je onderscheidt. Begin met je rol en ervaringsniveau, noem je belangrijkste technologieen en sluit af met het type uitdaging dat je zoekt. Vermijd holle frases zoals 'gepassioneerde teamspeler' zonder onderbouwing.", "Pas je profieltekst aan op de vacature. Solliciteer je op een frontend-rol, leg dan de nadruk op je React- en TypeScript-ervaring en je oog voor gebruikerservaring. Voor een backend- of platform-rol benadruk je juist architectuur, schaalbaarheid en cloud. Recruiters en ATS-systemen herkennen de match sneller als je vocabulaire aansluit op de functie.", "Maak je profieltekst concreet met cijfers en resultaten. In plaats van 'ervaren developer' werkt 'senior software engineer met acht jaar ervaring in schaalbare backendsystemen, die teams van vijf developers begeleidt' veel sterker. Zo combineer je niveau, specialisatie en leiderschap in een paar overtuigende regels."] },
    ],
    profileExamples: ["Junior software engineer met een afgeronde hbo-opleiding Informatica en een jaar ervaring met JavaScript, React en Node.js. Tijdens mijn afstudeerproject bouwde ik een webapplicatie met een REST API en een PostgreSQL-database, volledig getest met Jest. Ik leer snel, werk graag in Agile-teams en zoek een rol waarin ik mij kan ontwikkelen tot fullstack developer.", "Medior software engineer met vijf jaar ervaring in backendontwikkeling met Java en Spring Boot. Ik ontwikkel en onderhoud microservices in een cloudomgeving op AWS, met CI/CD via GitLab en containerisatie met Docker. In mijn huidige team verbeterde ik de testdekking van 45 naar 85 procent. Ik zoek een uitdagende rol waarin schaalbaarheid en codekwaliteit centraal staan.", "Senior software engineer en tech lead met tien jaar ervaring in het ontwerpen van schaalbare, cloud-native systemen op Azure en Kubernetes. Ik beheers C#, .NET en TypeScript en begeleid een team van zes developers in een Scrum-omgeving. Ik herontwierp een legacy-monoliet naar microservices, wat de deploytijd terugbracht van uren naar minuten. Ik zoek een rol met architectuur- en mentorverantwoordelijkheid."],
    relatedRoles: ["data-analist", "projectmanager", "grafisch-ontwerper"],
    faq: [
      { q: "Heb ik een hbo- of wo-diploma nodig om software engineer te worden?", a: "Een diploma helpt, maar is niet altijd verplicht. Veel werkgevers kijken vooral naar aantoonbare vaardigheden, een sterk portfolio en GitHub-projecten. Zelfstudie, bootcamps en relevante certificeringen kunnen een diploma deels vervangen, zeker als je concrete, werkende projecten kunt laten zien." },
      { q: "Welke programmeertalen leveren in 2025 het hoogste salaris op?", a: "Schaarse en specialistische talen zoals Rust, Go, Scala en Kotlin leveren vaak bovengemiddelde salarissen op, evenals expertise in cloud, data engineering en machine learning. Veelgevraagde talen als Python, Java, C# en TypeScript bieden de meeste vacatures en een solide salaris, vooral in combinatie met cloud- en DevOps-kennis." },
      { q: "Moet ik mijn GitHub of portfolio toevoegen aan mijn cv?", a: "Ja, voor technische functies is dat sterk aan te raden. Een link naar representatieve, opgeruimde projecten met een duidelijke README laat direct zien wat je kunt. Zorg dat de zichtbare repositories je beste werk tonen en verwijder of archiveer halve experimenten." },
      { q: "Hoe laat ik op mijn cv zien dat ik senior ben in plaats van medior?", a: "Toon impact en verantwoordelijkheid die verder gaan dan code schrijven. Denk aan architectuurbeslissingen, het begeleiden van junioren, code reviews, het opzetten van CI/CD en het vertalen van businessvraagstukken naar technische oplossingen. Kwantificeer resultaten zoals verbeterde uptime, kortere deploytijden of hogere testdekking." },
    ],
  },
  "verpleegkundige": {
    salary: { range: "EUR 2.800 - 4.200 bruto per maand", note: "Je salaris hangt af van je opleidingsniveau (mbo of hbo), je FWG-functieschaal, je ervaringsjaren, eventuele specialisaties en de onregelmatigheidstoeslag (ORT) voor avond-, nacht- en weekenddiensten, die het maandbedrag flink kan verhogen." },
    recruiterSkills: ["Medicatie toedienen en bewaken (VBM)", "Wond- en stomazorg", "Klinisch redeneren", "Elektronisch patientendossier (EPD)", "Reanimatie en BLS/ALS", "Infuus- en injectietechnieken", "Verpleegtechnische handelingen", "Patientgericht communiceren", "Multidisciplinair samenwerken", "BIG-registratie", "Triage en signaleren", "Stressbestendigheid en flexibiliteit"],
    sections: [
      { heading: "Hoeveel verdient een verpleegkundige?", body: ["Een verpleegkundige in Nederland verdient in 2025 gemiddeld tussen de EUR 2.800 en EUR 4.200 bruto per maand, exclusief toeslagen. Het exacte bedrag wordt bepaald door de cao (bijvoorbeeld de cao Ziekenhuizen, VVT of GGZ) en de bijbehorende FWG-functieschaal. Een mbo-verpleegkundige (niveau 4) start doorgaans lager dan een hbo-verpleegkundige (bachelor), die in een hogere schaal wordt ingedeeld.", "Een belangrijk en vaak onderschat onderdeel van het salaris is de onregelmatigheidstoeslag (ORT). Voor avond-, nacht- en weekenddiensten ontvang je een toeslag die per maand honderden euro's kan toevoegen aan je brutoloon. Wie veel onregelmatige diensten draait, komt netto aanzienlijk hoger uit dan het basissalaris suggereert.", "Specialisaties verhogen je salaris en je kansen op de arbeidsmarkt. IC-verpleegkundigen, SEH-verpleegkundigen, oncologie- en dialyseverpleegkundigen worden in hogere schalen ingedeeld vanwege de aanvullende opleiding en verantwoordelijkheid. Vermeld je specialisatie en je BIG-registratie daarom prominent op je cv, want werkgevers en ATS-systemen zoeken hier gericht op."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een verpleegkundige?", body: ["Werkgevers zoeken bij verpleegkundigen naar een combinatie van verpleegtechnische vaardigheden en sterke persoonlijke kwaliteiten. Op het technische vlak gaat het om handelingen zoals medicatie toedienen, wondverzorging, infuus- en injectietechnieken en het werken volgens protocollen. Vermeld concreet welke verpleegtechnische handelingen je bevoegd en bekwaam bent om uit te voeren.", "Klinisch redeneren is een kernvaardigheid die werkgevers expliciet benoemen. Het gaat om je vermogen om de situatie van een patient te observeren, te interpreteren en daar de juiste zorg op af te stemmen. Ook beheersing van het elektronisch patientendossier (EPD), zoals HiX of Epic, is tegenwoordig vrijwel altijd vereist. Noem het systeem waarmee je hebt gewerkt bij naam.", "Daarnaast zijn softskills onmisbaar in de zorg. Empathie, communicatie met patienten en familie, stressbestendigheid en flexibiliteit bij wisselende diensten zijn cruciaal. Omdat verpleegkundigen in multidisciplinaire teams werken met artsen, fysiotherapeuten en andere disciplines, weegt samenwerken zwaar mee. Onderbouw deze kwaliteiten met concrete voorbeelden uit je praktijk."] },
      { heading: "Veelgemaakte fouten op een verpleegkundige-cv", body: ["Een veelgemaakte fout is het niet of onduidelijk vermelden van de BIG-registratie. Voor verpleegkundigen is dit een wettelijke vereiste en werkgevers controleren hierop. Zet je BIG-nummer of de vermelding 'BIG-geregistreerd' duidelijk in je cv, samen met je opleidingsniveau (mbo-4 of hbo-bachelor), zodat er geen twijfel bestaat over je bevoegdheid.", "Een tweede fout is het te algemeen beschrijven van je werkervaring. 'Verleende zorg aan patienten' zegt weinig. Geef in plaats daarvan aan op welke afdeling je werkte, met welke patientgroep en welke verpleegtechnische handelingen je uitvoerde. Bijvoorbeeld: 'verpleegkundige op een chirurgische afdeling met 28 bedden, gespecialiseerd in postoperatieve wondzorg'.", "Ten derde vergeten veel verpleegkundigen hun bij- en nascholing te vermelden. De zorg verandert continu en werkgevers waarderen kandidaten die hun bevoegdheden actueel houden. Neem afgeronde scholingen, herregistraties van verpleegtechnische handelingen en certificaten zoals BLS, ALS of medicatieveiligheid expliciet op."] },
      { heading: "Welke opleiding en specialisaties heb je nodig als verpleegkundige?", body: ["Je kunt verpleegkundige worden via twee routes: de mbo-opleiding (niveau 4) leidt op tot mbo-verpleegkundige, en de hbo-opleiding (Bachelor of Nursing) tot hbo-verpleegkundige. Beide routes leiden tot een BIG-registratie, maar de hbo-opleiding biedt meer doorgroeimogelijkheden richting coordinerende, specialistische en regierollen. Vermeld je opleidingsniveau altijd duidelijk, omdat het bepalend is voor de functieschaal.", "Na je basisopleiding kun je je specialiseren via een vervolgopleiding, bijvoorbeeld tot IC-, SEH-, oncologie-, dialyse- of geriatrieverpleegkundige. Deze specialisaties duren een tot twee jaar, worden vaak duaal gevolgd naast je werk en leiden tot een hogere inschaling. Specialisten zijn op de krappe zorgarbeidsmarkt zeer gewild, dus een specialisatie versterkt je positie aanzienlijk.", "Wil je verder doorgroeien, dan zijn er paden naar verpleegkundig specialist (een masteropleiding met voorbehouden handelingen), praktijkverpleegkundige of leidinggevende functies. Geef op je cv aan welke richting je ambieert en welke scholing je daarvoor al hebt gevolgd, zodat werkgevers je groeipotentieel zien."] },
    ],
    profileExamples: ["Startend mbo-verpleegkundige (niveau 4), BIG-geregistreerd, met een afgeronde stage van tien maanden op een afdeling interne geneeskunde. Ik ben bekwaam in medicatie toedienen, wondverzorging en het werken met het EPD HiX. Ik ben empathisch, leergierig en flexibel inzetbaar in wisselende diensten. Ik zoek een functie waarin ik mijn verpleegtechnische vaardigheden verder kan uitbouwen.", "Ervaren hbo-verpleegkundige met acht jaar ervaring op een chirurgische afdeling met 28 bedden, BIG-geregistreerd. Ik ben gespecialiseerd in postoperatieve zorg en complexe wondverzorging en fungeer als aandachtsvelder wondzorg binnen mijn team. Ik werk gestructureerd, denk klinisch en begeleid regelmatig stagiairs. Ik zoek een uitdagende rol waarin ik mijn expertise kan inzetten en uitbreiden.", "IC-verpleegkundige met twaalf jaar ervaring en een afgeronde IC-vervolgopleiding, BIG-geregistreerd. Ik ben bekwaam in beademing, hemodynamische bewaking en het begeleiden van vitaal bedreigde patienten. Naast de directe patientenzorg ben ik praktijkbegeleider voor IC-leerlingen en lid van de reanimatiecommissie. Ik zoek een functie waarin specialistische zorg en het opleiden van collega's samenkomen."],
    relatedRoles: ["leraar", "hr-adviseur", "administratief-medewerker"],
    faq: [
      { q: "Wat is het verschil in salaris tussen een mbo- en hbo-verpleegkundige?", a: "Een hbo-verpleegkundige wordt doorgaans in een hogere FWG-functieschaal ingedeeld dan een mbo-verpleegkundige, wat een hoger basissalaris oplevert. Het exacte verschil hangt af van de cao en de functie, maar het loopt vaak op tot enkele honderden euro's bruto per maand. Specialisaties en ervaring kunnen het verschil verder vergroten." },
      { q: "Hoeveel scheelt de onregelmatigheidstoeslag (ORT) op mijn salaris?", a: "De ORT kan een aanzienlijk deel van je inkomen uitmaken. Voor verpleegkundigen die regelmatig avond-, nacht- en weekenddiensten draaien, komt er per maand vaak enkele honderden euro's bovenop het basissalaris. Het exacte percentage en de tijdvakken staan in je cao, zoals de cao Ziekenhuizen of VVT." },
      { q: "Moet ik mijn BIG-registratie op mijn cv vermelden?", a: "Ja, dit is essentieel. De BIG-registratie is wettelijk verplicht om als verpleegkundige te mogen werken en werkgevers controleren hierop. Vermeld duidelijk dat je BIG-geregistreerd bent, eventueel met je nummer, zodat recruiters direct zien dat je bevoegd bent." },
      { q: "Welke specialisaties zijn het meest gevraagd op de zorgarbeidsmarkt?", a: "IC-, SEH-, oncologie-, dialyse- en geriatrieverpleegkundigen zijn momenteel zeer gevraagd vanwege structurele tekorten. Deze specialisaties bieden niet alleen een hogere inschaling, maar ook ruime keuze in werkplek en goede doorgroeimogelijkheden richting verpleegkundig specialist." },
    ],
  },
  "marketing-manager": {
    salary: { range: "EUR 3.800 - 6.000 bruto per maand", note: "Je salaris hangt af van de grootte van het team en budget dat je beheert, je ervaring, de branche (tech en e-commerce betalen meer) en of de rol strategisch of meer uitvoerend is ingestoken." },
    recruiterSkills: ["Marketingstrategie en positionering", "Online marketing (SEO, SEA, SEM)", "Google Analytics 4 en GA-rapportage", "Social media marketing", "Contentmarketing en storytelling", "Marketing automation (HubSpot, Marketo)", "Budgetbeheer en ROI-analyse", "Campagnemanagement", "Conversieoptimalisatie (CRO)", "Teamleiding en stakeholdermanagement", "Merkstrategie en branding", "Datagedreven besluitvorming"],
    sections: [
      { heading: "Hoeveel verdient een marketing manager?", body: ["Een marketing manager in Nederland verdient in 2025 gemiddeld tussen de EUR 3.800 en EUR 6.000 bruto per maand. Een beginnend marketing manager of teamlead bij een kleiner bedrijf zit doorgaans rond de EUR 3.800 tot EUR 4.800, terwijl een ervaren marketing manager bij een groter bedrijf of in een commercieel sterke sector kan doorgroeien naar EUR 5.500 tot EUR 7.500 of meer.", "De omvang van je verantwoordelijkheid bepaalt veel. Beheer je een groot team en een aanzienlijk mediabudget, dan ligt je salaris hoger dan bij een rol die vooral uitvoerend is. Ook de branche telt mee: tech, SaaS, e-commerce en financiele dienstverlening betalen structureel beter dan bijvoorbeeld de non-profitsector of het onderwijs.", "Op directieniveau, zoals een Head of Marketing of Chief Marketing Officer, lopen de salarissen verder op en komt vaak een bonus- of resultaatregeling in beeld. Bij het onderhandelen helpt het om je impact concreet te maken met cijfers, zoals de omzetgroei, leadtoename of verbeterde ROAS die je hebt gerealiseerd."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een marketing manager?", body: ["Werkgevers zoeken bij een marketing manager naar een combinatie van strategisch inzicht en datagedreven uitvoering. Je moet een marketingstrategie kunnen vertalen naar concrete campagnes en kanalen, en tegelijk de resultaten kunnen meten en bijsturen. Kennis van online marketing, waaronder SEO, SEA en social media, is vrijwel altijd vereist, net als ervaring met analysetools zoals Google Analytics 4.", "Datagedreven werken is een onmisbare competentie geworden. Werkgevers verwachten dat je KPI's opstelt, campagnes optimaliseert op basis van data en de ROI van marketinginvesteringen kunt aantonen. Ervaring met marketing automation (zoals HubSpot of Marketo), conversieoptimalisatie en CRM-systemen is een sterk pluspunt. Noem deze tools letterlijk in je cv, omdat recruiters er gericht op scannen.", "Daarnaast wegen leiderschap en stakeholdermanagement zwaar. Als marketing manager geef je vaak leiding aan een team en werk je samen met sales, product en directie. Werkgevers letten op je vermogen om mensen aan te sturen, budgetten te beheren en marketing te verbinden aan bredere bedrijfsdoelen. Onderbouw deze vaardigheden met meetbare resultaten."] },
      { heading: "Veelgemaakte fouten op een marketing manager-cv", body: ["De grootste fout is een cv zonder meetbare resultaten. Voor een marketing manager is impact alles. Werkgevers willen geen lijst met taken zien, maar cijfers: 'verhoogde de organische traffic met 70 procent in een jaar', 'verlaagde de cost-per-lead met 35 procent' of 'realiseerde een ROAS van 5,2 op een mediabudget van EUR 500.000'. Kwantificeer je prestaties waar maar mogelijk.", "Een tweede fout is het verwarren van strategie en uitvoering. Solliciteer je op een managementrol, laat dan zien dat je verder kijkt dan losse campagnes. Beschrijf hoe je een strategie hebt opgezet, een team hebt aangestuurd en marketing hebt verbonden aan bedrijfsdoelen. Een cv dat alleen uitvoerende taken benoemt, oogt te junior voor een managementfunctie.", "Ten derde gebruiken veel kandidaten vage modewoorden zonder onderbouwing, zoals 'resultaatgericht' of 'creatieve denker'. Deze termen zeggen niets zonder bewijs. Vervang ze door concrete voorbeelden en resultaten. Vermeld bovendien de exacte tools en platforms die je beheerst, want generieke teksten vallen weg in de selectie door ATS-systemen."] },
      { heading: "Hoe schrijf je een sterke profieltekst als marketing manager?", body: ["Je profieltekst is je persoonlijke pitch en zet meteen de toon. Begin met je rol en ervaringsniveau, benoem je specialisatie (bijvoorbeeld online marketing, brand of growth) en sluit af met je grootste sterkte of ambitie. Een marketing manager wordt geacht overtuigend te communiceren, dus je profieltekst is meteen een proeve van bekwaamheid.", "Maak je profieltekst concreet en resultaatgericht. In plaats van 'ervaren marketeer met passie voor het vak' werkt 'marketing manager met acht jaar ervaring die een team van vijf aanstuurt en de online omzet in twee jaar verdubbelde' veel sterker. Combineer je niveau, je leiderschap en een tastbaar resultaat in een paar krachtige zinnen.", "Stem je profieltekst af op de vacature en de branche. Een growth-rol in een scale-up vraagt om een andere toon en focus dan een brandrol bij een groot merk. Door je woordkeuze en voorbeelden te laten aansluiten op de functie, herkent de werkgever de match direct."] },
    ],
    profileExamples: ["Beginnend marketing manager met vier jaar ervaring in online marketing en een afgeronde hbo-opleiding Commerciele Economie. Ik zette zelfstandig SEO- en social-mediacampagnes op en verhoogde de organische traffic van mijn werkgever met 60 procent in een jaar. Ik werk datagedreven met Google Analytics 4 en HubSpot en stuur een klein team van twee marketeers aan. Ik zoek een rol waarin ik mijn strategische vaardigheden verder kan ontwikkelen.", "Ervaren marketing manager met acht jaar ervaring in B2B-marketing binnen de techsector. Ik ontwikkel en realiseer integrale marketingstrategieen, stuur een team van vijf aan en beheer een jaarbudget van EUR 750.000. In mijn huidige rol verdubbelde ik het aantal gekwalificeerde leads in twee jaar en verbeterde ik de ROAS naar 4,8. Ik zoek een strategische rol waarin ik marketing en commercie kan verbinden.", "Strategisch marketing manager en growth specialist met elf jaar ervaring in e-commerce en SaaS. Ik bouwde marketingafdelingen op vanaf nul, leidde teams tot acht personen en realiseerde een omzetgroei van 150 procent over drie jaar via datagedreven growth-experimenten. Ik beheers het volledige spectrum van performance marketing, CRO en marketing automation. Ik zoek een leidende rol op directieniveau waarin ik groei kan aanjagen."],
    relatedRoles: ["data-analist", "grafisch-ontwerper", "verkoopmedewerker"],
    faq: [
      { q: "Welke opleiding heb ik nodig om marketing manager te worden?", a: "De meeste marketing managers hebben een hbo- of wo-opleiding in een richting als Commerciele Economie, Marketing, Communicatie of Bedrijfskunde. Belangrijker dan de exacte opleiding is aantoonbare ervaring met campagnes, data en het behalen van meetbare resultaten. Aanvullende certificeringen zoals Google Ads, Google Analytics of HubSpot versterken je profiel." },
      { q: "Hoe toon ik mijn marketingresultaten aan op mijn cv?", a: "Gebruik harde cijfers en koppel ze aan jouw bijdrage. Denk aan groei in organische traffic, daling van de cost-per-lead, verbetering van de conversieratio of ROAS en omzet- of leadgroei. Vermeld waar mogelijk het budget dat je beheerde en de omvang van het team dat je aanstuurde." },
      { q: "Welke tools moet ik beheersen als marketing manager in 2025?", a: "Werkgevers verwachten kennis van Google Analytics 4, Google Ads en social-advertentieplatforms, aangevuld met marketing automation zoals HubSpot of Marketo en een CRM-systeem. Kennis van SEO-tools, dashboards zoals Looker Studio en AI-gedreven marketingtools is een groeiend pluspunt." },
      { q: "Wat is het verschil tussen een marketing manager en een marketingspecialist?", a: "Een marketingspecialist richt zich op de uitvoering binnen een vakgebied, zoals SEO, content of social media. Een marketing manager is verantwoordelijk voor de strategie, het budget en vaak de aansturing van een team. Bij de managementrol ligt de nadruk op richting geven, prioriteren en marketing verbinden aan bredere bedrijfsdoelen." },
    ],
  },
  accountant: {
    salary: { range: "EUR 2.800 - 5.500 bruto per maand", note: "Een startende assistent-accountant verdient rond de EUR 2.800 tot 3.400 bruto per maand. Met een afgeronde RA- of AA-titel en enkele jaren ervaring loopt dit op tot EUR 4.500 tot 5.500. Senior accountants en managers bij de grote kantoren (Big Four) of in een controllersrol verdienen vaak meer, inclusief bonus en leaseauto." },
    recruiterSkills: ["Jaarrekeningen samenstellen en controleren", "Fiscale aangiften (VPB, IB, BTW)", "RA- of AA-registratie", "Exact Online en Twinfield", "IFRS en Nederlandse jaarverslaggeving (RJ)", "Auditmethodiek en interne controle", "Excel (draaitabellen, formules)", "Adviesvaardigheden richting MKB-klanten", "Analytisch en cijfermatig inzicht", "Power BI en datagedreven rapportage", "Wet- en regelgeving (Wwft, AVG)", "Nauwkeurigheid en integriteit"],
    sections: [
      { heading: "Hoeveel verdient een accountant?", body: ["Het salaris van een accountant in Nederland varieert sterk met opleiding, titel en ervaring. Een startende assistent-accountant begint doorgaans tussen EUR 2.800 en EUR 3.400 bruto per maand. Zodra je de AA- of RA-opleiding hebt afgerond en zelfstandig dossiers draait, stijgt dit naar EUR 4.000 tot EUR 5.500. Op je cv is het slim om je titel of de fase van je beroepsopleiding direct bij je functietitel te vermelden, want recruiters filteren daar actief op.", "De grootte en het type werkgever maken een wezenlijk verschil. De Big Four (Deloitte, PwC, EY, KPMG) en grote middelgrote kantoren betalen vaak iets meer en bieden bonussen, terwijl regionale MKB-kantoren compenseren met meer afwisseling en een betere werk-privebalans. Een controller of finance manager in het bedrijfsleven verdient regelmatig boven de EUR 6.000 bruto per maand.", "Wil je je onderhandelingspositie versterken? Kwantificeer op je cv het aantal dossiers dat je beheert, de omvang van de klantportefeuille in omzet en eventuele specialisaties zoals fiscaliteit of audit. Concrete cijfers maken je waarde voor een werkgever direct zichtbaar."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een accountant?", body: ["Werkgevers zoeken in de eerste plaats vakinhoudelijke zekerheid: het zelfstandig samenstellen van jaarrekeningen, het verzorgen van fiscale aangiften (VPB, IB en BTW) en kennis van de Nederlandse jaarverslaggeving (RJ) of IFRS. Vermeld deze concreet en koppel ze aan software die je beheerst, zoals Exact Online, Twinfield, AFAS of CaseWare. Veel ATS-systemen scannen op exact deze termen.", "Daarnaast is de adviserende rol steeds belangrijker geworden. Het kantoor verwacht dat je MKB-klanten proactief begeleidt bij financieringsvraagstukken, liquiditeitsplanning en fiscale optimalisatie. Soft skills als communicatie, klantgerichtheid en het vertalen van cijfers naar begrijpelijk advies onderscheiden je van de pure cijferaar.", "Tot slot wint datavaardigheid terrein. Kennis van Power BI, data-analyse en procesautomatisering maakt je aantrekkelijk, omdat kantoren hun controle- en samenstelprocessen digitaliseren. Een regel over Wwft-compliance en integriteit hoort er ook bij, gezien de poortwachtersrol van de accountant."] },
      { heading: "Veelgemaakte fouten op een accountant-cv", body: ["De grootste fout is vaag blijven over je verantwoordelijkheidsniveau. 'Werkzaam bij een accountantskantoor' zegt niets. Geef aan of je samenstelt of controleert, hoeveel dossiers je beheert, welke omvang die klanten hebben en of je eindverantwoordelijk bent. Recruiters willen je zelfstandigheid in een oogopslag kunnen inschatten.", "Een tweede valkuil is het weglaten van je opleidingsstatus. Vermeld duidelijk of je de AA- of RA-titel hebt behaald, of in welk jaar van de praktijkopleiding je zit. Onduidelijkheid hierover kost je sollicitaties, omdat het kantoor je inschaling en inzetbaarheid niet kan bepalen.", "Verder zien we vaak een opsomming van taken zonder resultaat. Schrijf niet 'verzorgde aangiften' maar 'verzorgde jaarlijks circa 120 BTW-aangiften en realiseerde een foutreductie van 30 procent door procesoptimalisatie'. Let ook op typefouten: voor een accountant is nauwkeurigheid een kernkwaliteit, dus een cv met slordigheden ondermijnt je geloofwaardigheid direct."] },
      { heading: "Welke opleiding en certificaten heb je nodig als accountant?", body: ["De meest gangbare route is een hbo- of wo-opleiding Accountancy, gevolgd door de wettelijk verplichte praktijkopleiding tot Accountant-Administratieconsulent (AA) of Registeraccountant (RA). De AA-titel is gericht op het MKB, de RA-titel op grotere controleopdrachten en het bedrijfsleven. Vermeld op je cv altijd in welke fase je zit; dit is een van de eerste dingen waar recruiters op letten.", "Aanvullende certificeringen versterken je profiel. Denk aan een fiscale specialisatie (bijvoorbeeld via de Register Belastingadviseur-route), permanente educatie (PE-punten) en cursussen in IFRS of specifieke software. Voor wie de overstap naar controlling overweegt, zijn een RC-titel (Register Controller) of een opleiding in business control waardevol.", "Geef je permanente educatie en recente bijscholing een plek op je cv. Dit laat zien dat je je kennis actueel houdt in een vakgebied waar wetgeving voortdurend verandert. Een korte regel met je laatst gevolgde cursussen kan net het verschil maken."] },
    ],
    profileExamples: ["Startende assistent-accountant met een afgeronde hbo-opleiding Accountancy en het eerste jaar van de AA-praktijkopleiding in uitvoering. Ervaring met het samenstellen van jaarrekeningen voor circa 40 MKB-klanten en het verzorgen van BTW- en IB-aangiften in Twinfield. Nauwkeurig, leergierig en sterk in het vertalen van cijfers naar heldere klantcommunicatie.", "Ervaren AA-accountant met 7 jaar ervaring binnen een middelgroot regionaal kantoor. Beheert zelfstandig een portefeuille van ruim 60 MKB-dossiers met een gezamenlijke omzet van EUR 45 miljoen. Specialist in fiscale optimalisatie en bedrijfsoverdrachten, met aantoonbare resultaten in klantbehoud (95 procent) en procesdigitalisering via Power BI.", "Registeraccountant (RA) met 10 jaar audit-ervaring bij de Big Four en aansturing van controleteams tot 8 personen. Diepgaande kennis van IFRS en interne beheersing, met eindverantwoordelijkheid voor jaarrekeningcontroles bij beursgenoteerde en internationale ondernemingen. Combineert technische diepgang met een adviserende, relatiegerichte aanpak."],
    relatedRoles: ["administratief-medewerker", "data-analist", "hr-adviseur"],
    faq: [
      { q: "Wat is het verschil tussen een AA- en RA-accountant op je cv?", a: "De AA-titel (Accountant-Administratieconsulent) richt zich vooral op het MKB en samenstelpraktijk, terwijl de RA-titel (Registeraccountant) is gericht op grotere controleopdrachten en het bedrijfsleven. Vermeld je titel direct bij je functienaam, zodat een recruiter je niveau meteen herkent." },
      { q: "Welke software vermeld je op een accountant-cv?", a: "Noem de pakketten die je daadwerkelijk beheerst, zoals Exact Online, Twinfield, AFAS, CaseWare en Excel op gevorderd niveau. Voeg datatools als Power BI toe als je daar ervaring mee hebt; veel kantoren scannen hier actief op." },
      { q: "Hoe laat je ervaring zien als startende accountant zonder veel werkjaren?", a: "Benoem je stages, studentassistentschappen en projecten met concrete cijfers, zoals het aantal verwerkte dossiers of aangiften. Combineer dit met je opleidingsstatus en relevante software om je inzetbaarheid aan te tonen." },
      { q: "Hoe lang mag een accountant-cv zijn?", a: "Houd het bij maximaal twee pagina's. Voor starters volstaat vaak een pagina. Focus op recente, relevante ervaring en kwantificeer je resultaten in plaats van alle taken op te sommen." },
    ],
  },
  leraar: {
    salary: { range: "EUR 2.800 - 5.200 bruto per maand", note: "Het salaris van een leraar wordt bepaald door de cao en de salarisschaal (L10 tot L12 in het voortgezet onderwijs, LA tot LB in het basisonderwijs). Een startende leraar zit rond EUR 2.800 tot 3.300 bruto per maand bij een volledige aanstelling. Ervaren docenten in hogere schalen bereiken EUR 4.500 tot 5.200. Bedragen gelden bij een fulltime dienstverband en zijn exclusief vakantiegeld en eindejaarsuitkering." },
    recruiterSkills: ["Lesbevoegdheid (eerste- of tweedegraads)", "Klassenmanagement", "Differentiatie en maatwerk", "Digitale lesmiddelen (Magister, Google Classroom)", "Pedagogisch-didactische vaardigheden", "Toetsing en beoordeling", "Ouder- en mentorgesprekken", "Curriculumontwikkeling", "Samenwerken in een team of sectie", "Omgaan met gedrag en zorgleerlingen", "Communicatieve vaardigheden", "Vakdidactiek van het eigen vak"],
    sections: [
      { heading: "Hoeveel verdient een leraar?", body: ["Het salaris van een leraar in Nederland ligt vast in de cao en is gekoppeld aan salarisschalen. In het basisonderwijs gelden de schalen L10 en hoger, in het voortgezet onderwijs lopen ze van L10 (tweedegraads) tot L11 en L12 (eerstegraads en bovenbouw). Een startende docent verdient bij een fulltime aanstelling rond EUR 2.800 tot EUR 3.300 bruto per maand. Vermeld op je cv je bevoegdheidsgraad, want die bepaalt rechtstreeks je inschaling.", "Met ervaring groei je binnen je schaal via periodieken, en met een eerstegraads bevoegdheid of een functiemix kun je doorstromen naar L11 of L12, wat oploopt tot EUR 4.500 tot EUR 5.200 bruto. Het onderwijs kent bovendien een ruime eindejaarsuitkering en goede secundaire voorwaarden, zoals een sterk pensioen en relatief veel vakantie.", "Werk je in deeltijd, wat in het onderwijs veel voorkomt, dan reken je het cao-bedrag naar rato om. Maak op je cv duidelijk hoeveel fte je gewend bent te draaien en welke schaal je hebt bereikt, zodat een schoolbestuur je positie snel kan inschatten."] },
      { heading: "Welke vaardigheden zoeken scholen bij een leraar?", body: ["Bovenaan staat de juiste bevoegdheid: scholen filteren direct op een eerste- of tweedegraads lesbevoegdheid voor het betreffende vak. Zet dit prominent in je profiel. Daarnaast is sterk klassenmanagement cruciaal: het vermogen om een veilige, gestructureerde leeromgeving te creeren waarin alle leerlingen tot leren komen.", "Differentiatie is een veelgevraagde competentie. Scholen willen docenten die les kunnen geven aan een gemengde groep en hun aanpak afstemmen op verschillende niveaus en zorgbehoeften. Beschrijf concreet hoe je dat doet, bijvoorbeeld met verlengde instructie, niveaugroepen of digitale adaptieve methodes.", "Digitale vaardigheid is geen luxe meer. Ervaring met Magister, SOMtoday, Google Classroom of Microsoft Teams hoort op je cv. Vul dit aan met sterke communicatie richting ouders en collega's en, indien van toepassing, ervaring als mentor. Dat laat zien dat je meer biedt dan alleen lesgeven."] },
      { heading: "Veelgemaakte fouten op een leraar-cv", body: ["De meest voorkomende fout is onduidelijkheid over je bevoegdheid. Vermeld expliciet of je eerste- of tweedegraads bevoegd bent, voor welk vak en welke onderwijssoort. Een school die dit niet meteen ziet, legt je cv vaak terzijde, omdat de bevoegdheid bepalend is voor je inzetbaarheid en inschaling.", "Een tweede fout is een cv vol algemeenheden zoals 'gepassioneerd over onderwijs' zonder onderbouwing. Maak je toegevoegde waarde concreet: noem het aantal leerlingen of klassen dat je begeleidde, projecten die je opzette, of een meetbaar resultaat zoals een verbeterd slagingspercentage of hogere leerlingtevredenheid.", "Tot slot vergeten veel docenten hun nevenactiviteiten en ontwikkeling te benoemen. Het opzetten van een nieuw lesprogramma, mentorschap, deelname aan een werkgroep of bijscholing maakt je profiel veel sterker. Houd je cv overzichtelijk op twee pagina's en plaats je meest relevante onderwijservaring bovenaan."] },
      { heading: "Hoe schrijf je een sterke profieltekst als leraar?", body: ["Een goede profieltekst staat bovenaan je cv en vat in drie tot vier zinnen samen wie je als docent bent. Begin met je bevoegdheid en vak, gevolgd door je jaren ervaring en het type school waar je werkte. Zo weet een lezer binnen enkele seconden of je past bij de vacature.", "Voeg vervolgens je onderscheidende kwaliteit toe. Ben je sterk in het motiveren van moeilijk bereikbare leerlingen, in het digitaliseren van lesmateriaal of juist in examenklassen? Onderbouw dit waar mogelijk met een cijfer, zoals een slagingspercentage of het aantal leerlingen dat je per jaar begeleidt.", "Sluit af met je pedagogische visie of ambitie, kort en authentiek. Vermijd holle frases en kies woorden die aansluiten bij de schoolcultuur uit de vacaturetekst. Een persoonlijke maar zakelijke toon werkt het beste in het onderwijs."] },
    ],
    profileExamples: ["Startende tweedegraads docent Engels met een afgeronde lerarenopleiding en een lesstage van 6 maanden in het vmbo en de onderbouw havo. Gaf zelfstandig les aan 5 klassen met in totaal circa 130 leerlingen en zette een digitale leeromgeving op in Google Classroom. Enthousiast, gestructureerd en sterk in het motiveren van leerlingen.", "Ervaren leraar basisonderwijs met 9 jaar ervaring in de groepen 5 tot en met 8 en aanvullende taken als rekencoordinator. Begeleidde jaarlijks gemiddeld 28 leerlingen, verbeterde de rekenresultaten met een aantoonbare stijging op de Cito-toets en coachte twee startende collega's. Specialist in differentiatie en omgaan met zorgleerlingen.", "Eerstegraads docent wiskunde (schaal LD/L12) met 12 jaar ervaring in de bovenbouw havo en vwo en eindverantwoordelijkheid voor examenklassen. Realiseerde meerdere jaren een slagingspercentage boven de 95 procent, ontwikkelde een vernieuwd PTA en gaf leiding aan de sectie wiskunde. Combineert vakdidactische diepgang met sterk mentoraat."],
    relatedRoles: ["hr-adviseur", "projectmanager", "marketing-manager"],
    faq: [
      { q: "Moet ik mijn lesbevoegdheid op mijn cv zetten?", a: "Ja, dit is het belangrijkste gegeven op een leraar-cv. Vermeld of je eerste- of tweedegraads bevoegd bent, voor welk vak en voor welke onderwijssoort. Scholen filteren hier direct op en zonder duidelijke bevoegdheid kom je vaak niet door de eerste selectie." },
      { q: "Hoe vermeld ik mijn ervaring als ik in deeltijd heb gewerkt?", a: "Geef per functie aan hoeveel fte of lesuren je draaide. Dat geeft een school een eerlijk en helder beeld van je inzet en voorkomt verkeerde aannames over je beschikbaarheid en ervaring." },
      { q: "Wat zet ik op mijn cv als ik nog geen onderwijservaring heb?", a: "Benadruk je lesstages, gastlessen, bijles of begeleiding van groepen in andere contexten, zoals sport of vrijwilligerswerk. Combineer dit met je behaalde of lopende lerarenopleiding en relevante digitale vaardigheden." },
      { q: "Welke digitale systemen zijn belangrijk voor een docent-cv?", a: "Noem leerlingvolg- en administratiesystemen zoals Magister of SOMtoday en digitale leeromgevingen zoals Google Classroom of Microsoft Teams. Ervaring met digitale en adaptieve lesmethodes is een sterke plus." },
    ],
  },
  projectmanager: {
    salary: { range: "EUR 3.500 - 7.000 bruto per maand", note: "Een junior projectmanager start rond EUR 3.500 tot EUR 4.200 bruto per maand. Met enkele jaren ervaring en het beheer van grotere budgetten en teams stijgt dit naar EUR 5.000 tot EUR 7.000. Senior project- en programmamanagers in IT, bouw of consultancy verdienen vaak meer, vaak aangevuld met bonus en leaseauto. Zzp-projectmanagers hanteren tarieven van EUR 75 tot EUR 125 per uur." },
    recruiterSkills: ["Projectplanning en -beheersing", "Budgetbeheer en forecasting", "Stakeholdermanagement", "Agile en Scrum", "Prince2 of PMI/PMP", "Risicomanagement", "Aansturen van multidisciplinaire teams", "MS Project, Jira en Confluence", "Rapportage aan directie en stuurgroep", "Onderhandelen en leveranciersmanagement", "Scope- en changemanagement", "Resultaatgericht en communicatief sterk"],
    sections: [
      { heading: "Hoeveel verdient een projectmanager?", body: ["Het salaris van een projectmanager hangt sterk af van de sector, de projectomvang en je ervaring. Een junior projectmanager begint doorgaans tussen EUR 3.500 en EUR 4.200 bruto per maand. Naarmate je verantwoordelijk wordt voor grotere budgetten, meer stakeholders en omvangrijkere teams, groeit dit naar EUR 5.000 tot EUR 7.000. Op je cv is het daarom essentieel om de schaal van je projecten te kwantificeren in budget, teamomvang en doorlooptijd.", "Sector maakt veel uit. Projectmanagers in IT, finance en consultancy zitten gemiddeld hoger dan in bijvoorbeeld de non-profit. Senior- en programmamanagers die meerdere projecten of een portfolio aansturen, verdienen vaak boven de EUR 7.000 bruto, regelmatig aangevuld met een bonus gekoppeld aan projectresultaten.", "Werk je als zelfstandige? Dan liggen uurtarieven doorgaans tussen EUR 75 en EUR 125, afhankelijk van specialisatie en certificering. Een Prince2- of PMP-certificaat en aantoonbaar succesvol afgeronde projecten rechtvaardigen een hoger tarief. Vermeld die resultaten concreet op je cv."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een projectmanager?", body: ["Werkgevers zoeken bewezen grip op de drie klassieke beheersaspecten: tijd, geld en scope. Laat zien dat je projecten binnen budget en planning oplevert en dat je scopewijzigingen beheerst via changemanagement. Concrete cijfers, zoals een project van EUR 2 miljoen binnen budget afgerond, zeggen meer dan welke functieomschrijving dan ook.", "Stakeholdermanagement is minstens zo belangrijk. Een projectmanager schakelt tussen directie, opdrachtgevers, leveranciers en het uitvoerende team. Communicatieve kracht, onderhandelingsvaardigheid en het managen van verwachtingen zijn doorslaggevend. Beschrijf hoe je een stuurgroep aanstuurde of een lastige stakeholder meekreeg.", "Methodologische kennis maakt je profiel concreet: Agile en Scrum voor iteratief werken, Prince2 of PMI/PMP voor gestructureerde projectbeheersing. Noem ook je tooling, zoals Jira, Confluence en MS Project. Vul dit aan met risicomanagement, want het tijdig signaleren en mitigeren van risico's is een kernverwachting."] },
      { heading: "Veelgemaakte fouten op een projectmanager-cv", body: ["De grootste fout is het beschrijven van projecten zonder context en resultaat. 'Verantwoordelijk voor diverse projecten' zegt niets. Geef per project het budget, de teamomvang, de doorlooptijd en het behaalde resultaat. Een recruiter wil de schaal van je verantwoordelijkheid direct kunnen inschatten.", "Een tweede valkuil is het verwarren van projectmanagement met algemene coordinatie. Maak duidelijk dat je eindverantwoordelijk was voor planning, budget en oplevering, en niet alleen ondersteunend. Gebruik actieve, resultaatgerichte werkwoorden en koppel ze aan meetbare uitkomsten zoals kostenbesparing, tijdwinst of klanttevredenheid.", "Verder vermelden veel kandidaten hun methodologieen en certificeringen niet of te vaag. Zet je Prince2-, PMP- of Scrum-certificaat duidelijk neer en geef aan in welke methode je werkt. Houd het cv strak op twee pagina's en zet je meest indrukwekkende projecten bovenaan, ondersteund door cijfers."] },
      { heading: "Welke certificaten helpen je als projectmanager?", body: ["Certificeringen zijn in projectmanagement een belangrijk selectiecriterium. Prince2 (Foundation en Practitioner) is in Nederland breed geaccepteerd en vaak een harde eis in vacatures. Voor een internationaal of meer methodisch profiel is de PMP-certificering van het PMI een sterke aanvulling. Vermeld het niveau en het jaar van behalen op je cv.", "Werk je in een agile omgeving, dan zijn certificaten als PSM (Professional Scrum Master), Certified ScrumMaster of SAFe waardevol. Veel organisaties werken hybride, dus een combinatie van klassieke en agile certificering maakt je breed inzetbaar. Geef in je profieltekst aan welke werkwijze je voorkeur heeft en waarom.", "Naast certificaten telt aantoonbare ervaring zwaarder dan ooit. Combineer je papieren kwalificaties met concrete projectresultaten. Een certificaat opent deuren, maar de cijfers over budgetten, teams en succesvolle opleveringen overtuigen de aannemende manager uiteindelijk."] },
    ],
    profileExamples: ["Junior projectmanager met een afgeronde hbo-opleiding en Prince2 Foundation-certificaat. Begeleidde als projectcoordinator meerdere deelprojecten met budgetten tot EUR 150.000 en teams van 5 personen. Gestructureerd, communicatief sterk en ervaren met Jira en MS Project. Klaar voor de stap naar volledige projectverantwoordelijkheid.", "Ervaren projectmanager met 6 jaar ervaring in IT-implementaties en Prince2 Practitioner- en PSM-certificering. Leverde meerdere projecten op met budgetten tot EUR 1,5 miljoen en multidisciplinaire teams van 12 personen, consequent binnen tijd en budget. Sterk in stakeholdermanagement en het sturen op meetbare resultaten.", "Senior project- en programmamanager met 12 jaar ervaring in de financiele sector en PMP-certificering. Verantwoordelijk voor een projectportfolio met een totaal budget van EUR 8 miljoen en aansturing van 4 projectleiders. Realiseerde een gemiddelde kostenbesparing van 15 procent en een verbeterde oplevertijd door procesoptimalisatie en strak risicomanagement."],
    relatedRoles: ["software-engineer", "marketing-manager", "data-analist"],
    faq: [
      { q: "Welk certificaat heb ik nodig als projectmanager?", a: "In Nederland is Prince2 (Foundation en Practitioner) het meest gevraagd, vaak aangevuld met PMP voor een internationaal profiel of PSM/Scrum voor agile teams. Vermeld het behaalde niveau en jaartal duidelijk op je cv." },
      { q: "Hoe kwantificeer ik mijn projecten op mijn cv?", a: "Geef per project het budget, de teamomvang, de doorlooptijd en het resultaat, zoals kostenbesparing of tijdige oplevering. Deze cijfers laten een recruiter direct de schaal en het succes van je werk zien." },
      { q: "Wat is het verschil tussen een projectmanager en een projectcoordinator op een cv?", a: "Een projectmanager is eindverantwoordelijk voor planning, budget en oplevering, terwijl een coordinator vooral ondersteunt. Maak dit onderscheid expliciet, omdat het je seniority en inschaling bepaalt." },
      { q: "Moet ik zowel agile als watervalervaring vermelden?", a: "Ja, veel organisaties werken hybride. Door zowel agile (Scrum) als klassieke methodes (Prince2) te benoemen, laat je zien dat je je werkwijze kunt aanpassen aan de organisatie en het type project." },
    ],
  },
  verkoopmedewerker: {
    salary: { range: "EUR 2.100 - 3.200 bruto per maand", note: "Een verkoopmedewerker verdient doorgaans tussen EUR 2.100 en EUR 2.700 bruto per maand bij een fulltime dienstverband, afhankelijk van de cao (bijvoorbeeld Retail Non-Food) en leeftijd. Met ervaring, een specialisatie of een rol als senior of teamleider loopt dit op tot EUR 3.200 of meer. In branches met provisie, zoals elektronica of telecom, komt daar een variabele beloning bovenop." },
    recruiterSkills: ["Klantgerichtheid en service", "Verkoop- en adviesvaardigheden", "Kassasystemen en afrekenen", "Productkennis", "Voorraadbeheer en bestellingen", "Upselling en cross-selling", "Omgaan met klachten", "Commercieel inzicht", "Samenwerken in een team", "Representatief en stressbestendig", "Talenkennis (Nederlands en Engels)", "Flexibiliteit in werktijden"],
    sections: [
      { heading: "Hoeveel verdient een verkoopmedewerker?", body: ["Het salaris van een verkoopmedewerker wordt grotendeels bepaald door de cao van de branche, je leeftijd en je ervaring. Bij een fulltime dienstverband ligt het brutosalaris doorgaans tussen EUR 2.100 en EUR 2.700 per maand. In de retail gelden cao's zoals Retail Non-Food, terwijl winkels in bijvoorbeeld mode, elektronica of doe-het-zelf eigen afspraken kunnen hebben.", "Met ervaring en aanvullende verantwoordelijkheden, zoals het aansturen van een team, het beheren van voorraad of het draaien van openings- en sluitingsdiensten, stijgt het salaris richting EUR 3.000 tot EUR 3.200. Een doorgroei naar senior verkoopmedewerker, assistent-bedrijfsleider of bedrijfsleider levert een hoger inkomen op.", "In commerciele branches verdien je vaak een vast basissalaris met provisie of bonus op basis van je verkoopresultaten. Vermeld op je cv concrete cijfers, zoals een omzetstijging of het behalen van verkooptargets. Dat onderscheidt je direct van kandidaten die alleen hun taken opsommen."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een verkoopmedewerker?", body: ["Klantgerichtheid staat met afstand bovenaan. Werkgevers zoeken iemand die klanten vriendelijk en deskundig adviseert, behoeften herkent en daarop inspeelt. Beschrijf op je cv hoe je dit doet en koppel het waar mogelijk aan resultaat, zoals een hoge klanttevredenheid of terugkerende klanten.", "Commercieel inzicht is een tweede kernpunt. Werkgevers waarderen verkopers die actief upsellen en cross-sellen en die bijdragen aan de omzet- en margedoelstellingen van de winkel. Noem concrete prestaties, bijvoorbeeld het structureel halen of overtreffen van je verkooptargets of een bijdrage aan een omzetstijging.", "Daarnaast tellen praktische vaardigheden mee: ervaring met kassasystemen, voorraadbeheer en het afhandelen van klachten. Soft skills zoals stressbestendigheid tijdens piekdrukte, een representatief voorkomen en goed kunnen samenwerken in een team maken je profiel compleet. Talenkennis is een plus, zeker in winkels met internationaal publiek."] },
      { heading: "Veelgemaakte fouten op een verkoopmedewerker-cv", body: ["De meest gemaakte fout is een cv dat alleen taken opsomt zonder resultaten. 'Hielp klanten en stond aan de kassa' onderscheidt je van niemand. Vertaal je werk naar prestaties: behaalde targets, een omzetstijging, een hoge klanttevredenheidsscore of het zelfstandig openen en sluiten van de winkel.", "Een tweede fout is een onpersoonlijk of slordig cv. In een commerciele rol draait het om presentatie. Een verzorgde, foutloze lay-out en een korte, krachtige profieltekst laten zien dat je representatief en zorgvuldig bent, precies de eigenschappen die op de winkelvloer tellen.", "Tot slot onderschatten veel kandidaten het belang van flexibiliteit en beschikbaarheid. Werkgevers in de retail zoeken mensen die in weekenden, avonden en tijdens piekperiodes kunnen werken. Vermeld je beschikbaarheid expliciet en benoem relevante ervaring met drukke verkoopperiodes zoals de feestdagen of uitverkoop."] },
      { heading: "Hoe kun je doorgroeien als verkoopmedewerker?", body: ["Een verkoopfunctie biedt vaak meer doorgroeimogelijkheden dan mensen denken. Vanuit een rol als verkoopmedewerker kun je opklimmen naar senior verkoopmedewerker, assistent-bedrijfsleider en uiteindelijk bedrijfsleider of filiaalmanager. Laat op je cv zien dat je extra verantwoordelijkheden hebt opgepakt, zoals het inwerken van nieuwe collega's of het beheren van een afdeling.", "Specialisatie is een andere route. Verdiep je in een productgroep, word visual merchandiser, of stap door naar een rol in inkoop of accountmanagement. Branchecursussen en certificaten, bijvoorbeeld in verkooptechnieken of productkennis, versterken je profiel en je doorgroeikansen.", "Wil je hogerop? Benoem dan op je cv concrete resultaten en initiatieven die je leiderschap en commerciele waarde aantonen. Denk aan het overtreffen van targets, het verbeteren van de winkelpresentatie of het opzetten van een verkoopactie. Dit maakt je een logische kandidaat voor een volgende stap."] },
    ],
    profileExamples: ["Enthousiaste verkoopmedewerker met 2 jaar ervaring in de mode-retail en een sterk klantgericht instinct. Behaalde consequent de persoonlijke verkooptargets en droeg bij aan een omzetstijging van 8 procent op de eigen afdeling. Ervaren met kassasystemen, voorraadbeheer en het zelfstandig openen en sluiten van de winkel.", "Ervaren verkoopmedewerker met 5 jaar ervaring in de elektronicabranche en een uitstekende productkennis. Overtrof structureel de maandtargets met gemiddeld 12 procent door gericht advies en upselling, en behandelde klachten met een hoge klanttevredenheid. Werkte een team van 4 nieuwe collega's in en draaide zelfstandig piekdiensten.", "Senior verkoopmedewerker en aankomend assistent-bedrijfsleider met 8 jaar retailervaring. Verantwoordelijk voor de dagelijkse aansturing van een team van 6 medewerkers, het voorraadbeheer en de winkelpresentatie. Realiseerde een jaarlijkse omzetgroei van 10 procent en zette succesvolle verkoopacties op tijdens piekperiodes."],
    relatedRoles: ["administratief-medewerker", "logistiek-medewerker", "marketing-manager"],
    faq: [
      { q: "Wat zet ik op mijn cv als ik nog geen verkoopervaring heb?", a: "Benadruk klantgerichte ervaring uit bijvoorbeeld bijbanen, horeca, stages of vrijwilligerswerk. Leg de nadruk op communicatie, samenwerken en commercieel inzicht, en benoem je beschikbaarheid en motivatie voor de verkoop." },
      { q: "Hoe laat ik mijn verkoopresultaten zien op mijn cv?", a: "Gebruik concrete cijfers, zoals behaalde targets, een omzetstijging in procenten of een klanttevredenheidsscore. Cijfers maken je toegevoegde waarde direct zichtbaar en onderscheiden je van kandidaten die alleen taken opsommen." },
      { q: "Is een diploma nodig om verkoopmedewerker te worden?", a: "Een specifiek diploma is meestal geen vereiste, hoewel een mbo-opleiding in detailhandel of verkoop een pluspunt is. Werkgevers letten vooral op klantgerichtheid, commerciele instelling en relevante werkervaring." },
      { q: "Hoe vermeld ik mijn beschikbaarheid op een retail-cv?", a: "Geef expliciet aan op welke dagen en dagdelen je beschikbaar bent, inclusief avonden en weekenden. Flexibiliteit is in de retail een belangrijk selectiecriterium en vergroot je kans op een uitnodiging." },
    ],
  },
  "data-analist": {
    salary: { range: "EUR 2.900 - 5.500 bruto per maand", note: "Een junior data-analist start doorgaans rond 2.900 tot 3.300 euro bruto per maand. Met 3 tot 5 jaar ervaring ligt het salaris rond 3.800 tot 4.300 euro, en senior data-analisten of analisten met specialisatie in Python en machine learning verdienen 4.500 tot 5.500 euro. In de Randstad en bij grote corporates of consultancybureaus liggen de bedragen 10 tot 15 procent hoger." },
    recruiterSkills: ["SQL", "Python (pandas, NumPy)", "Power BI", "Tableau", "Excel (draaitabellen, Power Query)", "Datavisualisatie", "Statistiek en hypothesetoetsing", "ETL en datacleaning", "Stakeholdermanagement", "Google Analytics 4", "A/B-testen", "Storytelling met data"],
    sections: [
      { heading: "Hoeveel verdient een data-analist in Nederland?", body: ["Het salaris van een data-analist hangt sterk af van je ervaring, je technische vaardigheden en de sector waarin je werkt. Beginnende data-analisten verdienen in 2025 gemiddeld 2.900 tot 3.300 euro bruto per maand. Na een paar jaar ervaring groeit dit door naar 3.800 tot 4.300 euro. Senior data-analisten die complexe analyses en machine learning-modellen bouwen, verdienen tot 5.500 euro bruto per maand.", "De sector maakt een groot verschil. In de financiele dienstverlening, tech en consultancy liggen de salarissen structureel hoger dan in de publieke sector of de zorg. Ook de regio telt mee: in Amsterdam, Utrecht en Eindhoven betalen werkgevers gemiddeld 10 tot 15 procent meer dan in het noorden of zuiden van het land.", "Wil je je salaris verhogen? Investeer in schaarse vaardigheden zoals Python, cloud-platformen (Azure, AWS, Snowflake) en het vertalen van data naar concrete business-beslissingen. Juist die combinatie van techniek en communicatie maakt het verschil aan de onderhandelingstafel."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een data-analist?", body: ["Werkgevers zoeken in de eerste plaats naar harde technische vaardigheden. SQL is vrijwel altijd een vereiste, gevolgd door een visualisatietool zoals Power BI of Tableau en steeds vaker Python voor geavanceerde analyses. Vermeld deze tools letterlijk in je cv, want recruiters en ATS-systemen filteren op exacte termen.", "Naast techniek zijn analytisch denkvermogen en statistische kennis cruciaal. Kun je een dataset opschonen, patronen herkennen en betrouwbare conclusies trekken? Laat dit zien met concrete voorbeelden, bijvoorbeeld: 'Bouwde een Power BI-dashboard dat de rapportagetijd met 60 procent verkortte.'", "Onderschat de zachte vaardigheden niet. Een data-analist die complexe inzichten begrijpelijk kan uitleggen aan het management is goud waard. Stakeholdermanagement, storytelling met data en het vertalen van cijfers naar actie zijn vaardigheden die je nadrukkelijk in je profiel en werkervaring naar voren mag laten komen."] },
      { heading: "Welke veelgemaakte fouten staan op een data-analist-cv?", body: ["De grootste fout is een cv vol vage uitspraken zonder cijfers. 'Verantwoordelijk voor data-analyse' zegt niets. Beschrijf in plaats daarvan de impact: welke beslissing of besparing kwam voort uit jouw analyse? Kwantificeer waar mogelijk met percentages, euro's of tijdsbesparing.", "Een tweede veelgemaakte fout is het opsommen van tientallen tools zonder onderscheid in niveau. Geef aan welke tools je dagelijks gebruikt en op welk niveau (basis, gevorderd, expert). Een lange lijst zonder context werkt averechts en oogt ongeloofwaardig.", "Tot slot vergeten veel kandidaten hun cv af te stemmen op de vacature en op ATS-systemen. Gebruik trefwoorden uit de vacaturetekst, kies een strakke en goed leesbare opmaak, en vermijd afbeeldingen of tabellen die door scansoftware verkeerd worden gelezen. Een schoon, trefwoordrijk cv komt vaker door de eerste selectie."] },
      { heading: "Welke opleiding en certificaten heb je nodig als data-analist?", body: ["Voor de meeste functies wordt een hbo- of wo-diploma gevraagd in een kwantitatieve richting, zoals econometrie, informatica, wiskunde, business analytics of bedrijfskunde. Steeds vaker tellen aantoonbare vaardigheden echter zwaarder dan de exacte studierichting, zeker als je een portfolio met projecten kunt laten zien.", "Certificaten versterken je cv en bewijzen je actuele kennis. Populair en gewild zijn de Microsoft Certified: Power BI Data Analyst Associate, Google Data Analytics Professional Certificate, Tableau Desktop Specialist en certificeringen in SQL of Python. Vermeld de behaalde certificaten met jaartal in een apart blok.", "Heb je geen klassieke achtergrond? Een goed gevuld portfolio op GitHub of een persoonlijke projectpagina kan het verschil maken. Toon concrete analyses, dashboards en code. Werkgevers waarderen aantoonbaar zelflerend vermogen en praktijkervaring vaak meer dan een papieren diploma alleen."] },
    ],
    profileExamples: ["Enthousiaste startende data-analist met een afgeronde hbo-opleiding Business Analytics en sterke vaardigheden in SQL, Excel en Power BI. Tijdens mijn afstudeerproject bouwde ik een dashboard dat de handmatige rapportage met 50 procent verkortte. Leergierig, nauwkeurig en gedreven om data om te zetten in concrete inzichten.", "Ervaren data-analist met 5 jaar ervaring in de retail- en financiele sector. Gespecialiseerd in SQL, Python en Power BI, met aantoonbaar resultaat: ontwikkelde voorspellende modellen die de voorraadkosten met 18 procent verlaagden. Sterk in het vertalen van complexe data naar heldere adviezen voor het management.", "Senior data-analist en specialist in machine learning met 8 jaar ervaring. Bouwde end-to-end data-pipelines in Azure en Snowflake en leidde een team van 3 analisten. Realiseerde onder meer een klantsegmentatiemodel dat de marketing-ROI met 25 procent verhoogde. Combineert diepe technische kennis met sterke stakeholdercommunicatie."],
    relatedRoles: ["software-engineer", "marketing-manager", "accountant"],
    faq: [
      { q: "Wat is het verschil tussen een data-analist en een data scientist?", a: "Een data-analist richt zich op het analyseren van bestaande data om beslissingen te ondersteunen, vaak met SQL, Excel en visualisatietools. Een data scientist gaat een stap verder met statistische modellen, machine learning en programmeren om voorspellingen te doen. De data scientist-rol vereist doorgaans meer wiskundige en programmeerkennis." },
      { q: "Heb ik Python nodig om data-analist te worden?", a: "Voor instapfuncties is Python niet altijd verplicht; SQL en een visualisatietool zoals Power BI zijn vaak voldoende. Voor doorgroei en hogere salarissen is Python echter een groot pluspunt, omdat je daarmee complexere analyses en automatiseringen kunt uitvoeren. Het loont om er vroeg in te investeren." },
      { q: "Hoe lang moet een cv van een data-analist zijn?", a: "Houd je cv bij voorkeur op een tot twee A4'tjes. Voor starters volstaat een pagina; ervaren analisten mogen uitlopen naar twee. Focus op relevante projecten, meetbare resultaten en de tools die je beheerst, in plaats van een uitputtende opsomming van elke taak." },
      { q: "Welke woorden moet ik gebruiken om door een ATS-systeem te komen?", a: "Neem de exacte termen uit de vacature over, zoals 'SQL', 'Power BI', 'datavisualisatie', 'ETL' en 'stakeholdermanagement'. Vermijd creatieve opmaak, kolommen en afbeeldingen die scansoftware in de war brengen. Een eenvoudige, trefwoordrijke layout vergroot je kans om de eerste digitale selectie te passeren." },
    ],
  },
  "hr-adviseur": {
    salary: { range: "EUR 3.000 - 5.000 bruto per maand", note: "Een startende HR-adviseur verdient rond 3.000 tot 3.500 euro bruto per maand. Met enkele jaren ervaring groeit dit naar 3.800 tot 4.500 euro. Senior HR-adviseurs of HR business partners bij grotere organisaties verdienen 4.500 tot 5.500 euro. Specialisaties zoals arbeidsrecht, recruitment of organisatieontwikkeling kunnen het salaris verder verhogen." },
    recruiterSkills: ["Arbeidsrecht en cao-kennis", "Werving en selectie", "Verzuimbegeleiding (Wet poortwachter)", "Performance management", "AFAS of Visma HR-systemen", "Gesprekstechnieken en coaching", "Onboarding", "Functiewaardering", "Strategische personeelsplanning", "Adviesvaardigheden", "Conflicthantering", "HR-analytics"],
    sections: [
      { heading: "Hoeveel verdient een HR-adviseur?", body: ["Het salaris van een HR-adviseur in Nederland ligt in 2025 gemiddeld tussen 3.000 en 5.000 euro bruto per maand. Starters beginnen rond 3.000 tot 3.500 euro, terwijl ervaren HR-adviseurs met een breed takenpakket richting 4.500 euro gaan. Senior HR business partners die strategisch meedenken met de directie kunnen meer dan 5.000 euro verdienen.", "De omvang en sector van de organisatie spelen een grote rol. Bij multinationals, de financiele sector en de overheid liggen de salarissen doorgaans hoger dan bij het mkb of in de non-profit. Ook een specialisatie in arbeidsrecht, verzuim of recruitment kan je salaris merkbaar opkrikken.", "Wil je doorgroeien in salaris? Ontwikkel je van uitvoerend HR-medewerker naar strategisch adviseur. Werkgevers belonen HR-professionals die niet alleen processen beheren, maar ook meetbaar bijdragen aan personeelsbehoud, productiviteit en een sterke bedrijfscultuur."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een HR-adviseur?", body: ["Werkgevers verwachten van een HR-adviseur een sterke combinatie van kennis en mensgerichtheid. Gedegen kennis van arbeidsrecht, cao's en de Wet verbetering poortwachter is vrijwel altijd vereist. Vermeld deze kennisgebieden expliciet, want ze vormen de basis van een betrouwbaar HR-advies.", "Daarnaast zijn communicatieve en adviesvaardigheden doorslaggevend. Een HR-adviseur schakelt dagelijks tussen medewerkers, leidinggevenden en directie. Coachende gesprekstechnieken, conflicthantering en het vermogen om met tact lastige boodschappen te brengen, zijn vaardigheden die je in je profiel en werkervaring mag onderbouwen met voorbeelden.", "Steeds vaker wordt ook datagedreven werken gevraagd. Kennis van HR-systemen zoals AFAS of Visma en het kunnen analyseren van verzuim-, verloop- en wervingscijfers maken je aantrekkelijker. Laat zien dat je niet alleen adviseert op onderbuikgevoel, maar je adviezen onderbouwt met concrete cijfers."] },
      { heading: "Welke veelgemaakte fouten staan op een HR-adviseur-cv?", body: ["Een veelvoorkomende fout is dat HR-adviseurs hun cv te algemeen houden. 'Verantwoordelijk voor HR-taken' zegt weinig. Maak concreet welke processen je beheerde en met welk resultaat, bijvoorbeeld: 'Verlaagde het ziekteverzuim van 6 naar 4 procent binnen een jaar door een nieuw verzuimbeleid.'", "Een tweede fout is het onderbelichten van adviesimpact. HR draait om mensen en resultaten; toon dus hoe jouw advies bijdroeg aan minder verloop, snellere werving of een betere medewerkerstevredenheid. Cijfers maken je verhaal geloofwaardig en onderscheidend.", "Tot slot vergeten kandidaten vaak hun systeem- en wetskennis te benoemen. Vermeld concreet welke HR-systemen je beheerst en welke wettelijke kaders je toepast. Een cv dat zowel de menselijke als de juridische en administratieve kant van HR laat zien, wekt direct meer vertrouwen bij recruiters."] },
      { heading: "Hoe groei je door als HR-adviseur?", body: ["De klassieke doorgroei loopt van HR-medewerker naar HR-adviseur, en vervolgens naar HR business partner of HR-manager. Een HR business partner werkt nauw samen met het management en vertaalt bedrijfsdoelen naar personeelsbeleid. Om die stap te maken, is strategisch inzicht en kennis van organisatieontwikkeling onmisbaar.", "Specialiseren is een tweede route. Je kunt je verdiepen in arbeidsrecht, recruitment, learning en development, of arbeidsvoorwaarden en beloning. Specialisten zijn schaars en daardoor vaak goed betaald. Een aanvullende opleiding, zoals een posthbo arbeidsrecht of een recruitment-certificering, versterkt je positie.", "Investeer ook in HR-analytics en verandermanagement. Organisaties zoeken HR-professionals die data kunnen vertalen naar beleid en die transities zoals reorganisaties of cultuurveranderingen kunnen begeleiden. Wie deze vaardigheden combineert, maakt sneller de stap naar een strategische en beter betaalde rol."] },
    ],
    profileExamples: ["Gedreven startende HR-adviseur met een afgeronde hbo-opleiding Human Resource Management. Tijdens mijn stage begeleidde ik zelfstandig 12 wervingstrajecten en ondersteunde ik het verzuimbeleid. Sterk in luisteren, organiseren en het toepassen van actuele arbeidsrechtkennis. Op zoek naar een rol waarin ik mensen en organisatie verder kan helpen groeien.", "Ervaren HR-adviseur met 6 jaar ervaring in het mkb en de zorg. Brede kennis van arbeidsrecht, cao's en verzuimbegeleiding volgens de Wet poortwachter. Verlaagde bij mijn huidige werkgever het ziekteverzuim van 6 naar 4 procent en verkortte de gemiddelde wervingstijd met 20 procent. Communicatief sterk en oplossingsgericht.", "Strategische HR business partner en specialist in organisatieontwikkeling met 10 jaar ervaring. Adviseerde directies bij twee reorganisaties en implementeerde een nieuw performance-managementsysteem dat de medewerkerstevredenheid met 15 punten verhoogde. Combineert diepgaande arbeidsrechtkennis met datagedreven HR-analytics en sterk verandermanagement."],
    relatedRoles: ["administratief-medewerker", "projectmanager", "marketing-manager"],
    faq: [
      { q: "Welke opleiding heb je nodig om HR-adviseur te worden?", a: "De meest gangbare route is een hbo-opleiding Human Resource Management of een verwante richting zoals bedrijfskunde of toegepaste psychologie. Met een wo-diploma in arbeids- en organisatiepsychologie kun je sneller doorgroeien naar strategische functies. Aanvullende cursussen in arbeidsrecht of verzuim versterken je profiel." },
      { q: "Wat is het verschil tussen een HR-adviseur en een HR business partner?", a: "Een HR-adviseur richt zich vooral op operationeel en tactisch advies rond werving, verzuim en arbeidsvoorwaarden. Een HR business partner werkt strategischer en is een vaste sparringpartner van het management, gericht op het verbinden van personeelsbeleid aan bedrijfsdoelen. De business partner-rol vraagt meer ervaring en strategisch inzicht." },
      { q: "Welke certificaten zijn waardevol voor een HR-adviseur?", a: "Waardevolle certificaten zijn onder meer een posthbo Arbeidsrecht, certificeringen in verzuimmanagement, recruitment (zoals een sourcing- of intercedentenopleiding) en trainingen in coaching of gesprekstechnieken. Ook kennis van veelgebruikte HR-systemen zoals AFAS is een sterk pluspunt op je cv." },
      { q: "Hoe laat ik mensgerichtheid zien op mijn HR-cv?", a: "Toon mensgerichtheid met concrete voorbeelden in plaats van losse karaktereigenschappen. Beschrijf bijvoorbeeld hoe je een conflict tussen medewerkers oploste, een verzuimtraject succesvol begeleidde of de onboarding verbeterde. Resultaten zoals een hogere medewerkerstevredenheid of lager verloop maken je mensgerichtheid geloofwaardig." },
    ],
  },
  "grafisch-ontwerper": {
    salary: { range: "EUR 2.600 - 4.500 bruto per maand", note: "Een junior grafisch ontwerper start doorgaans rond 2.600 tot 3.000 euro bruto per maand. Met enkele jaren ervaring groeit dit naar 3.200 tot 3.900 euro. Senior ontwerpers, art directors en specialisten in UX of motion design verdienen 4.000 tot 5.000 euro. Freelancers rekenen vaak 45 tot 85 euro per uur, afhankelijk van ervaring en specialisme." },
    recruiterSkills: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign", "Figma", "Huisstijl en branding", "Typografie", "Drukwerkvoorbereiding (DTP)", "UX/UI-design", "After Effects en motion design", "Conceptontwikkeling", "Kleurtheorie", "Portfolio"],
    sections: [
      { heading: "Hoeveel verdient een grafisch ontwerper?", body: ["Het salaris van een grafisch ontwerper in Nederland varieert in 2025 tussen 2.600 en 4.500 euro bruto per maand. Beginnende ontwerpers verdienen rond 2.600 tot 3.000 euro, terwijl ontwerpers met enkele jaren ervaring richting 3.500 tot 3.900 euro gaan. Senior ontwerpers en art directors verdienen 4.000 euro of meer.", "Je specialisatie maakt een groot verschil. Grafisch ontwerpers die zich verbreden naar UX/UI-design of motion design zijn schaars en verdienen daardoor vaak bovengemiddeld. Ook het type werkgever telt: reclamebureaus en techbedrijven betalen doorgaans meer dan kleine studio's of de creatieve non-profit.", "Veel grafisch ontwerpers werken als freelancer. De uurtarieven liggen tussen 45 en 85 euro, afhankelijk van ervaring, specialisme en klantkring. Een sterk portfolio en een herkenbare eigen stijl zijn doorslaggevend om hogere tarieven te kunnen vragen en opdrachtgevers aan je te binden."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een grafisch ontwerper?", body: ["Beheersing van de Adobe Creative Suite is voor vrijwel elke vacature een harde eis. Photoshop, Illustrator en InDesign vormen de basis. Vermeld deze programma's expliciet en geef aan op welk niveau je werkt. Steeds vaker wordt ook Figma gevraagd, vooral voor digitaal en interface-ontwerp.", "Naast software draait het om vakinhoudelijk inzicht: typografie, kleurtheorie, compositie en conceptontwikkeling. Werkgevers willen zien dat je niet alleen mooie beelden maakt, maar dat je ontwerpkeuzes onderbouwt vanuit een merk- en communicatiedoel. Laat dit terugkomen in de beschrijving van je projecten.", "Het allerbelangrijkste is je portfolio. Geen enkel cv overtuigt zonder sterk en goed gecureerd werk. Voeg een directe link naar je online portfolio toe en kies projecten die aansluiten bij de functie. Toon waar mogelijk het resultaat van je werk, zoals een geslaagde rebranding of een campagne met meetbaar bereik."] },
      { heading: "Welke veelgemaakte fouten staan op een grafisch-ontwerper-cv?", body: ["De grootste fout is geen of een zwakke portfoliolink. Voor een grafisch ontwerper is het portfolio belangrijker dan het cv zelf. Zorg voor een werkende, professionele link naar je beste werk en zet die prominent bovenaan. Een cv zonder portfolio wordt zelden serieus bekeken.", "Een tweede fout is een overdreven of onleesbaar vormgegeven cv. Een grafisch ontwerper mag laten zien dat hij vormgeving beheerst, maar de inhoud moet altijd helder en scanbaar blijven. Overdaad aan kleuren, lettertypes of effecten leidt af en kan onprofessioneel overkomen. Houd het strak en doordacht.", "Tot slot vergeten ontwerpers vaak hun rol en impact te benoemen. Beschrijf niet alleen wat je maakte, maar ook voor wie en met welk effect. Bijvoorbeeld: 'Ontwierp een nieuwe huisstijl voor een retailmerk, wat leidde tot 30 procent meer naamsbekendheid.' Context en resultaat maken je werk waardevoller."] },
      { heading: "Hoe maak je een sterk portfolio als grafisch ontwerper?", body: ["Een sterk portfolio toont kwaliteit boven kwantiteit. Selecteer 8 tot 12 van je beste projecten in plaats van alles wat je ooit maakte. Kies werk dat past bij het soort opdrachten of de functie die je nastreeft, en zorg voor variatie die toch een herkenbare eigen stijl laat zien.", "Vertel bij elk project een kort verhaal: wat was de opdracht, welk probleem loste je op en wat was het resultaat? Opdrachtgevers en recruiters willen je denkproces zien, niet alleen het eindbeeld. Een goede case-beschrijving onderscheidt een professional van een hobbyist.", "Presenteer je werk online via een eigen website, Behance of een PDF-portfolio, en houd het actueel. Zorg dat het op mobiel goed werkt en snel laadt. Voeg de link toe aan je cv, LinkedIn en sollicitatiemail, zodat opdrachtgevers met een klik je beste werk kunnen bekijken."] },
    ],
    profileExamples: ["Creatieve junior grafisch ontwerper met een afgeronde mbo- of hbo-opleiding Grafische Vormgeving en sterke beheersing van Photoshop, Illustrator en InDesign. Tijdens mijn stage ontwierp ik een complete social-mediacampagne die het bereik van de klant met 40 procent verhoogde. Leergierig, oog voor detail en gedreven om merken visueel sterk neer te zetten. Portfolio op aanvraag of via mijn website.", "Ervaren grafisch ontwerper met 5 jaar ervaring bij een reclamebureau en als freelancer. Gespecialiseerd in huisstijl, branding en drukwerkvoorbereiding, met aanvullende kennis van Figma. Ontwikkelde onder meer een rebranding voor een mkb-klant die leidde tot 30 procent meer naamsbekendheid. Combineert conceptueel denken met strakke uitvoering.", "Senior grafisch ontwerper en art director met 9 jaar ervaring en specialisatie in branding en motion design. Leidde creatieve teams en realiseerde campagnes voor landelijke merken. Verzorgde de visuele identiteit van een lancering die binnen 6 maanden 1 miljoen impressies behaalde. Sterk in conceptontwikkeling, klantadvies en het bewaken van merkconsistentie."],
    relatedRoles: ["marketing-manager", "software-engineer", "verkoopmedewerker"],
    faq: [
      { q: "Heb ik een diploma nodig om grafisch ontwerper te worden?", a: "Een diploma is geen harde eis; in de creatieve sector telt je portfolio het zwaarst. Veel ontwerpers hebben wel een mbo- of hbo-opleiding Grafische Vormgeving of Communication & Multimedia Design gevolgd. Aantoonbare vaardigheden en sterk werk wegen echter vaak zwaarder dan het papiertje alleen." },
      { q: "Welke software moet een grafisch ontwerper beheersen?", a: "De Adobe Creative Suite is de standaard: Photoshop voor beeldbewerking, Illustrator voor vectorwerk en InDesign voor opmaak en drukwerk. Voor digitaal en interface-ontwerp is Figma steeds belangrijker, en voor animatie After Effects. Vermeld per programma op welk niveau je werkt." },
      { q: "Hoe presenteer ik mijn portfolio op mijn cv?", a: "Zet een werkende link naar je online portfolio prominent bovenaan je cv, vlak bij je contactgegevens. Kies een professionele presentatievorm zoals een eigen website, Behance of een verzorgde PDF. Selecteer alleen je beste en meest relevante werk en zorg dat de link op elk apparaat goed werkt." },
      { q: "Wat verdient een freelance grafisch ontwerper per uur?", a: "Freelance grafisch ontwerpers rekenen in 2025 doorgaans 45 tot 85 euro per uur. Het tarief hangt af van je ervaring, specialisme en klantenkring. Specialisten in UX, branding of motion design kunnen hogere tarieven vragen. Houd bij je tarief rekening met belasting, verzekeringen en niet-declarabele uren." },
    ],
  },
  "logistiek-medewerker": {
    salary: { range: "EUR 2.200 - 3.300 bruto per maand", note: "Een startende logistiek medewerker verdient rond 2.200 tot 2.500 euro bruto per maand. Met ervaring en aanvullende certificaten zoals een heftruck- of reachtruckcertificaat groeit dit naar 2.600 tot 3.000 euro. Teamleiders en logistiek coordinatoren verdienen 3.000 tot 3.500 euro of meer. Onregelmatigheids- en ploegentoeslagen kunnen het maandsalaris flink verhogen." },
    recruiterSkills: ["Heftruckcertificaat", "Reachtruckcertificaat", "Orderpicken", "Voorraadbeheer", "WMS (warehouse management systeem)", "Scannen en registreren", "VCA-certificaat", "Nauwkeurig werken", "Fysiek belastbaar", "Verpakken en verzendklaar maken", "Werken onder tijdsdruk", "Teamwork"],
    sections: [
      { heading: "Hoeveel verdient een logistiek medewerker?", body: ["Het salaris van een logistiek medewerker ligt in 2025 gemiddeld tussen 2.200 en 3.300 euro bruto per maand. Starters beginnen rond het minimumloon tot 2.500 euro, terwijl medewerkers met ervaring en de juiste certificaten doorgroeien naar 2.600 tot 3.000 euro. Logistiek coordinatoren en teamleiders verdienen meer.", "Toeslagen maken in de logistiek een groot verschil. Veel magazijnen en distributiecentra werken in ploegen, waardoor je onregelmatigheidstoeslag, avond- of nachttoeslag en weekendtoeslag kunt ontvangen. Deze toeslagen kunnen je netto-inkomen aanzienlijk verhogen ten opzichte van het basissalaris.", "Certificaten lonen direct. Een heftruck- of reachtruckcertificaat, een VCA-diploma of kennis van een warehouse management systeem (WMS) maken je breder inzetbaar en daarmee waardevoller. Wie zich ontwikkelt richting coordinatie of voorraadbeheer, kan zijn salaris structureel verhogen."] },
      { heading: "Welke vaardigheden zoeken werkgevers bij een logistiek medewerker?", body: ["Werkgevers letten in de logistiek sterk op concrete, aantoonbare vaardigheden. Certificaten zoals een heftruck-, reachtruck- of VCA-certificaat zijn vaak een directe voorwaarde. Vermeld deze prominent op je cv, bij voorkeur in een apart blok, want recruiters scannen er als eerste op.", "Daarnaast zijn nauwkeurigheid, snelheid en fysieke belastbaarheid belangrijk. In een magazijn draait alles om foutloos orderpicken, correct registreren en het halen van targets. Laat zien dat je betrouwbaar en efficient werkt, bijvoorbeeld: 'Behaalde structureel een picknauwkeurigheid van 99,8 procent.'", "Ook ervaring met systemen telt mee. Kennis van een warehouse management systeem (WMS), scanapparatuur en voorraadbeheer maakt je aantrekkelijker. Combineer dit met goede samenwerking en flexibiliteit voor ploegendiensten, en je laat zien dat je een betrouwbare kracht bent waar werkgevers op kunnen bouwen."] },
      { heading: "Welke veelgemaakte fouten staan op een logistiek-medewerker-cv?", body: ["Een veelgemaakte fout is het verstoppen of weglaten van certificaten. Voor logistieke functies zijn heftruck-, reachtruck- en VCA-certificaten vaak doorslaggevend. Zet ze duidelijk in een apart kopje met de geldigheidsdatum, zodat een recruiter in een oogopslag ziet dat je inzetbaar bent.", "Een tweede fout is een vaag takenoverzicht zonder cijfers. 'Werkzaam in het magazijn' zegt weinig. Maak concreet wat je deed en met welk resultaat, bijvoorbeeld: 'Pickte gemiddeld 120 orders per dag met een nauwkeurigheid van 99 procent.' Cijfers laten je betrouwbaarheid en tempo zien.", "Tot slot onderschatten kandidaten het belang van flexibiliteit en beschikbaarheid. Veel logistieke werkgevers zoeken mensen die in ploegen of weekenden kunnen werken. Benoem expliciet je beschikbaarheid en bereidheid tot onregelmatige diensten; dat kan net het verschil maken in een krappe selectie."] },
      { heading: "Welke certificaten heb je nodig als logistiek medewerker?", body: ["Voor veel logistieke functies is geen specifieke vooropleiding nodig, maar tellen certificaten des te zwaarder. Het heftruckcertificaat en het reachtruckcertificaat zijn de meest gevraagde, omdat ze je direct inzetbaar maken voor het verplaatsen en stapelen van goederen. Beide zijn in korte tijd te behalen.", "Het VCA-certificaat (Veiligheid, Gezondheid en Milieu Checklist Aannemers) is in veel magazijnen en distributiecentra verplicht. Het toont aan dat je veilig kunt werken volgens de geldende richtlijnen. Werkgevers zien dit als een belangrijk pluspunt en soms zelfs als harde eis.", "Wil je doorgroeien? Verdiep je in voorraadbeheer, logistieke processen of een warehouse management systeem. Aanvullende opleidingen zoals een mbo-opleiding Logistiek medewerker of cursussen logistiek management openen de deur naar functies als logistiek coordinator of teamleider, met bijbehorend hoger salaris."] },
    ],
    profileExamples: ["Gemotiveerde logistiek medewerker met een geldig heftruck- en reachtruckcertificaat en een VCA-diploma. Fysiek belastbaar, nauwkeurig en gewend om in ploegendiensten te werken. Tijdens mijn vorige functie pickte ik gemiddeld 110 orders per dag met een nauwkeurigheid van 99 procent. Beschikbaar voor onregelmatige diensten en gericht op snel en foutloos werken.", "Ervaren logistiek medewerker met 6 jaar ervaring in distributiecentra. Brede kennis van orderpicken, voorraadbeheer en werken met een WMS en scanapparatuur. Behaalde structureel de dagtargets met een picknauwkeurigheid van 99,7 procent en draaide regelmatig de rol van aanspreekpunt voor nieuwe collega's. In bezit van heftruck-, reachtruck- en VCA-certificaat.", "Allround logistiek medewerker en aankomend coordinator met 9 jaar ervaring. Verantwoordelijk voor voorraadbeheer, inkoopregistratie en het aansturen van een team van 5 collega's. Optimaliseerde het pickproces waardoor de doorlooptijd met 15 procent daalde. Combineert hands-on magazijnervaring met kennis van logistieke processen en WMS-systemen."],
    relatedRoles: ["administratief-medewerker", "verkoopmedewerker", "verpleegkundige"],
    faq: [
      { q: "Heb ik een diploma nodig om logistiek medewerker te worden?", a: "Een specifiek diploma is meestal niet vereist voor instapfuncties in de logistiek. Werkgevers letten vooral op certificaten zoals heftruck, reachtruck en VCA, op je inzet en op je beschikbaarheid. Voor doorgroei naar coordinerende functies helpt een mbo-opleiding Logistiek wel." },
      { q: "Welke certificaten maken mijn logistiek-cv sterker?", a: "De meest waardevolle certificaten zijn het heftruckcertificaat, het reachtruckcertificaat en het VCA-diploma. Ook ervaring met een warehouse management systeem (WMS) en scanapparatuur is een sterk pluspunt. Zet je certificaten met geldigheidsdatum in een apart blok bovenaan je cv." },
      { q: "Hoe laat ik op mijn cv zien dat ik snel en nauwkeurig werk?", a: "Gebruik concrete cijfers in je werkervaring. Vermeld bijvoorbeeld hoeveel orders je gemiddeld per dag pickte en met welke nauwkeurigheid, of hoe vaak je de dagtargets haalde. Meetbare resultaten overtuigen werkgevers meer dan algemene termen als 'snel' of 'precies'." },
      { q: "Moet ik mijn beschikbaarheid voor ploegendiensten op mijn cv zetten?", a: "Ja, dat is een sterk pluspunt. Veel logistieke werkgevers werken met ploegen, avond-, nacht- of weekenddiensten. Vermeld expliciet dat je flexibel beschikbaar bent en bereid bent in ploegen te werken; dit kan je kansen in een krappe selectie merkbaar vergroten." },
    ],
  },
};

export function getEnrichment(slug: string): Enrichment {
  return CV_ENRICHMENT[slug] ?? {};
}
